const quizDataJp = [
  // {
  //   check: 'G1_kamei',
  //   question: 'この問題の答えはなんでしょう',
  //   a: 'Take My Hand',
  //   b: 'When The Sun Goes Down',
  //   c: 'Song 2',
  //   d: 'Rewind',
  //   explanation: 'この問題の答えはCです',
  // },




  ////// 中１
  //// 中１ 亀井
  // 中１ 亀井 英語
  {
    check: 'G1_kamei_E',
    question:'「私は学生ではありません」正しい英文はどれか',
    a:'I am not a student.',
    b:'I am a student.',
    c:'I is not a student.',
    d:'I are not a student.',
    explanation:'否定文の文章ではis/am/areの後ろにnotを付ける',
  },
  {
    check: 'G1_kamei_E',
    question:'「水曜日」はどれか',
    a:'Wednesday',
    b:'Thursday',
    c:'Saturday',
    d:'Monday',
    explanation:'Thursday「木曜日」・Saturday「土曜日」・Monday「月曜日」',
  },
  {
    check: 'G1_kamei_E',
    question:'「１２月」はどれか',
    a:'December',
    b:'June',
    c:'January',
    d:'Novemver',
    explanation:'June「６月」・January「１月」・Novemver「１１月」',
  },
  {
    check: 'G1_kamei_E',
    question:'「２月」はどれか',
    a:'February',
    b:'August',
    c:'October',
    d:'May',
    explanation:'August「８月」・October「１０月」・May「５月」',
  },
  {
    check: 'G1_kamei_E',
    question:'Are you a tennis player?（Yesで答える）',
    a:"Yes,I am.",
    b:"Yes,I do",
    c:"No,I'm not.",
    d:"No,I don't.",
    explanation:"Are you～？で聞かれたら「Yes,I am」か「No,I'm not」で答える",
  },
  {
    check: 'G1_kamei_E',
    question:'Do you like a grape?（Noで答える）',
    a:"No,I don't.",
    b:"Yes,I am.",
    c:"No,I'm not.",
    d:"Yes,I do.",
    explanation:"Do you～?で聞かれたら「Yes,I do」か「No,I don't」で答える",
  },
  {
    check: 'G1_kamei_E',
    question:'「３月」はどれか',
    a:'March',
    b:'April',
    c:'July',
    d:'September',
    explanation:'April「４月」・July「７月」・September「９月」',
  },
  {
    check: 'G1_kamei_E',
    question:'「冬」はどれか',
    a:'winter',
    b:'spring',
    c:'fall',
    d:'summer',
    explanation:'spring「春」・summer「夏」・fall(autumn)「秋」',
  },
  // 中１ 亀井 数学
  {
    check: 'G1_kamei_M',
    question: '500円の利益を「＋500」と表すとき、「－300」は何を表している？',
    a: '300円の損失',
    b: '300円の利益',
    c: '－300円の損失',
    d: '－300円の値段',
    explanation: '答え：300円の損失',
  },
  {
    check: 'G1_kamei_M',    
    question: '絶対値が4より小さい整数はいくつある？',
    a: '7個',
    b: '9個',
    c: '4個',
    d: '8個',
    explanation: '答え：7個\n －3，－2，－1，0，1，2，3の7個ですね。\n負の数が含まれることや、「より小さい」という言葉の意味に注意しましょう。',
  },
  {
    check: 'G1_kamei_M',
    question: '絶対値が等しい2つの数があり、その差が6であるとき、\nこの2つの数のうち、小さい方の数はいくつ？',
    a: '－3',
    b: '＋3',
    c: '－6',
    d: '＋6',
    explanation: '答え：－3\n 0をはさんで両側に6離れているわけですから、\n 2つの数の正体は＋3と－3ですね。',
  },
  {
    check: 'G1_kamei_M',
    question: '3－（－5）＝？',
    a: '8',
    b: '－2',
    c: '2',
    d: '－13',
    explanation: '答え：8\n間違えた人は計算問題をしっかり復習しましょう！',
  },
  {
    check: 'G1_kamei_M',
    question: '平均点より5点上であることの成績を「＋5点」を表すとき、\n 68点を取ったA君の成績は「－7点」でした。\nこのとき成績が「＋4点」だったB君の点数は何点？',
    a: '79点',
    b: '75点',
    c: '71点',
    d: '57点',
    explanation: '答え：79点\n A君が68点で「－7点」なので平均点は75点、\n B君は「＋4点」なので75＋4＝79ですね。',
  },
  {
    check: 'G1_kamei_M',    
    question: '（－6）×（－2）＝？',
    a: '12',
    b: '－12',
    c: '－3',
    d: '3',
    explanation: '答え：12\n間違えた人は計算問題をしっかり復習しましょう！',
  },
  {
    check: 'G1_kamei_M',
    question: '(－2²)と(－2)²はどちらが大きい？',
    a: '(－2)²',
    b: '(－2²)',
    c: '同じ大きさ',
    d: 'これだけでは決まらない',
    explanation: '答え：(－2)²\n(－2²)＝－2×2＝－4\n(－2)²＝(－2)×(－2)＝4になります。',
  },
  {
    check: 'G1_kamei_M',
    question: '20.23×51.84＋48.16×20.23＝？',
    a: '2023',
    b: '2097.4464',
    c: '1948.5536',
    d: '3141.5926',
    explanation: '答え：2023\n分配法則を使えば暗算でもできますね！',
  },

  // 中１ 亀井 理科
  {
    check: 'G1_kamei_SI',
    question: '次のうち自ら動き回る生物はどれか。',
    a: 'アメーバ',
    b: 'ミカヅキモ',
    c: 'アオミドロ',
    d: 'ボルボックス',
    explanation: 'アメーバ以外の生物は日光の力をかりて、自ら養分をつくる「光合成」というはたらきをします。',
  },
  {
    check: 'G1_kamei_SI',
    question: 'ルーペを使うとき、見てはいけないものは何か。',
    a: '太陽',
    b: '人',
    c: '虫',
    d: '動物',
    explanation: '',
  },
  {
    check: 'G1_kamei_SI',
    question: '顕微鏡を使うとき、最初に取り付けるものは何か。',
    a: '接眼レンズ',
    b: '対物レンズ',
    c: 'レボルバー',
    d: '反射鏡',
    explanation: '',
  },
  {
    check: 'G1_kamei_SI',
    question: '顕微鏡で観察したとき、観察したいものが左下に見えた。視野の中央に移動させるには、プレパラートをどの方向に動かせばよいか。',
    a: '左下',
    b: '右下',
    c: '左上',
    d: '右上',
    explanation: '顕微鏡では左右上下逆に見えます。',
  },
  {
    check: 'G1_kamei_SI',
    question: '顕微鏡で観察をするとき、レンズを付けた後にすることは何か。',
    a: '反射鏡としぼりで視野の明るさを調整する。',
    b: '対物レンズとプレパラートの距離をできるだけ近づける。',
    c: 'レボルバーを回し、高倍率の対物レンズにする。',
    d: '調節ねじでピントを合わせる',
    explanation: '',
  },
  {
    check: 'G1_kamei_SI',
    question: 'めしべの先端の部分を何というか。',
    a: '柱頭',
    b: 'やく',
    c: 'がく',
    d: '子房',
    explanation: '',
  },
  {
    check: 'G1_kamei_SI',
    question: 'おしべの先端にあるやくには何が入っているか。',
    a: '花粉',
    b: '胚珠',
    c: '種子',
    d: '子房',
    explanation: '',
  },
  {
    check: 'G1_kamei_SI',
    question: '20～40倍程度に拡大でき、物体を立体的にみることができる顕微鏡を何というか。',
    a: '双眼実体顕微鏡',
    b: '金属顕微鏡',
    c: '生物顕微鏡',
    d: 'デジタル顕微鏡',
    explanation: '双眼実体顕微鏡は物体の向きはそのままで、立体的にみることができます。',
  },
  {
    check: 'G1_kamei_SI',
    question: '10倍の接眼レンズと15倍の対物レンズを使った場合、観察する倍率は何倍になるか。',
    a: '150倍',
    b: '75倍',
    c: '25倍',
    d: '12.5倍',
    explanation: '観察倍率はそれぞれのレンズの倍率をかけたものになります。',
  },
  {
    check: 'G1_kamei_SI',
    question: 'スケッチをするときの注意点として正しくないものはどれか。',
    a: 'わかりやすいように色を塗る',
    b: '二度書きしない',
    c: '影はつけない',
    d: 'わかりやいように細い線で描く',
    explanation: '',
  },
  // 中１ 亀井 社会

  //// 中１ 龍華
  // 中１ 龍華 英語
  {
    check: 'G1_ryuge_E',
    question:'「私は学生ではありません」正しい英文はどれか',
    a:'I am not a student.',
    b:'I am a student.',
    c:'I is not a student.',
    d:'I are not a student.',
    explanation:'否定文の文章ではis/am/areの後ろにnotを付ける',
  },
  {
    check: 'G1_ryuge_E',
    question:'「水曜日」はどれか',
    a:'Wednesday',
    b:'Thursday',
    c:'Saturday',
    d:'Monday',
    explanation:'Thursday「木曜日」・Saturday「土曜日」・Monday「月曜日」',
  },
  {
    check: 'G1_ryuge_E',
    question:'「１２月」はどれか',
    a:'December',
    b:'June',
    c:'January',
    d:'Novemver',
    explanation:'June「６月」・January「１月」・Novemver「１１月」',
  },
  {
    check: 'G1_ryuge_E',
    question:'「２月」はどれか',
    a:'February',
    b:'August',
    c:'October',
    d:'May',
    explanation:'August「８月」・October「１０月」・May「５月」',
  },
  {
    check: 'G1_ryuge_E',
    question:'Are you a tennis player?（Yesで答える）',
    a:"Yes,I am.",
    b:"Yes,I do",
    c:"No,I'm not.",
    d:"No,I don't.",
    explanation:"Are you～？で聞かれたら「Yes,I am」か「No,I'm not」で答える",
  },
  {
    check: 'G1_ryuge_E',
    question:'Do you like a grape?（Noで答える）',
    a:"No,I don't.",
    b:"Yes,I am.",
    c:"No,I'm not.",
    d:"Yes,I do.",
    explanation:"Do you～?で聞かれたら「Yes,I do」か「No,I don't」で答える",
  },
  {
    check: 'G1_ryuge_E',
    question:'「３月」はどれか',
    a:'March',
    b:'April',
    c:'July',
    d:'September',
    explanation:'April「４月」・July「７月」・September「９月」',
  },
  {
    check: 'G1_ryuge_E',
    question:'「冬」はどれか',
    a:'winter',
    b:'spring',
    c:'fall',
    d:'summer',
    explanation:'spring「春」・summer「夏」・fall(autumn)「秋」',
  },
  // 中１ 龍華 数学
  {
    check: 'G1_ryuge_M',
    question: '500円の利益を「＋500」と表すとき、「－300」は何を表している？',
    a: '300円の損失',
    b: '300円の利益',
    c: '－300円の損失',
    d: '－300円の値段',
    explanation: '答え：300円の損失',
  },
  {
    check: 'G1_ryuge_M',    
    question: '絶対値が4より小さい整数はいくつある？',
    a: '7個',
    b: '9個',
    c: '4個',
    d: '8個',
    explanation: '答え：7個\n －3，－2，－1，0，1，2，3の7個ですね。\n負の数が含まれることや、「より小さい」という言葉の意味に注意しましょう。',
  },
  {
    check: 'G1_ryuge_M',
    question: '絶対値が等しい2つの数があり、その差が6であるとき、\nこの2つの数のうち、小さい方の数はいくつ？',
    a: '－3',
    b: '＋3',
    c: '－6',
    d: '＋6',
    explanation: '答え：－3\n 0をはさんで両側に6離れているわけですから、\n 2つの数の正体は＋3と－3ですね。',
  },
  {
    check: 'G1_ryuge_M',
    question: '3－（－5）＝？',
    a: '8',
    b: '－2',
    c: '2',
    d: '－13',
    explanation: '答え：8\n間違えた人は計算問題をしっかり復習しましょう！',
  },
  {
    check: 'G1_ryuge_M',
    question: '平均点より5点上であることの成績を「＋5点」を表すとき、\n 68点を取ったA君の成績は「－7点」でした。\nこのとき成績が「＋4点」だったB君の点数は何点？',
    a: '79点',
    b: '75点',
    c: '71点',
    d: '57点',
    explanation: '答え：79点\n A君が68点で「－7点」なので平均点は75点、\n B君は「＋4点」なので75＋4＝79ですね。',
  },
  {
    check: 'G1_ryuge_M',    
    question: '（－6）×（－2）＝？',
    a: '12',
    b: '－12',
    c: '－3',
    d: '3',
    explanation: '答え：12\n間違えた人は計算問題をしっかり復習しましょう！',
  },
  {
    check: 'G1_ryuge_M',
    question: '(－2²)と(－2)²はどちらが大きい？',
    a: '(－2)²',
    b: '(－2²)',
    c: '同じ大きさ',
    d: 'これだけでは決まらない',
    explanation: '答え：(－2)²\n(－2²)＝－2×2＝－4\n(－2)²＝(－2)×(－2)＝4になります。',
  },
  {
    check: 'G1_ryuge_M',
    question: '20.23×51.84＋48.16×20.23＝？',
    a: '2023',
    b: '2097.4464',
    c: '1948.5536',
    d: '3141.5926',
    explanation: '答え：2023\n分配法則を使えば暗算でもできますね！',
  },

  // 中１ 龍華 理科
  {
    check: 'G1_ryuge_SI',
    question: '次のうち自ら動き回る生物はどれか。',
    a: 'アメーバ',
    b: 'ミカヅキモ',
    c: 'アオミドロ',
    d: 'ボルボックス',
    explanation: 'アメーバ以外の生物は日光の力をかりて、自ら養分をつくる「光合成」というはたらきをします。',
  },
  {
    check: 'G1_ryuge_SI',
    question: 'ルーペを使うとき、見てはいけないものは何か。',
    a: '太陽',
    b: '人',
    c: '虫',
    d: '動物',
    explanation: '',
  },
  {
    check: 'G1_ryuge_SI',
    question: '顕微鏡を使うとき、最初に取り付けるものは何か。',
    a: '接眼レンズ',
    b: '対物レンズ',
    c: 'レボルバー',
    d: '反射鏡',
    explanation: '',
  },
  {
    check: 'G1_ryuge_SI',
    question: '顕微鏡で観察したとき、観察したいものが左下に見えた。視野の中央に移動させるには、プレパラートをどの方向に動かせばよいか。',
    a: '左下',
    b: '右下',
    c: '左上',
    d: '右上',
    explanation: '顕微鏡では左右上下逆に見えます。',
  },
  {
    check: 'G1_ryuge_SI',
    question: '顕微鏡で観察をするとき、レンズを付けた後にすることは何か。',
    a: '反射鏡としぼりで視野の明るさを調整する。',
    b: '対物レンズとプレパラートの距離をできるだけ近づける。',
    c: 'レボルバーを回し、高倍率の対物レンズにする。',
    d: '調節ねじでピントを合わせる',
    explanation: '',
  },
  {
    check: 'G1_ryuge_SI',
    question: 'めしべの先端の部分を何というか。',
    a: '柱頭',
    b: 'やく',
    c: 'がく',
    d: '子房',
    explanation: '',
  },
  {
    check: 'G1_ryuge_SI',
    question: 'おしべの先端にあるやくには何が入っているか。',
    a: '花粉',
    b: '胚珠',
    c: '種子',
    d: '子房',
    explanation: '',
  },
  {
    check: 'G1_ryuge_SI',
    question: '20～40倍程度に拡大でき、物体を立体的にみることができる顕微鏡を何というか。',
    a: '双眼実体顕微鏡',
    b: '金属顕微鏡',
    c: '生物顕微鏡',
    d: 'デジタル顕微鏡',
    explanation: '双眼実体顕微鏡は物体の向きはそのままで、立体的にみることができます。',
  },
  {
    check: 'G1_ryuge_SI',
    question: '10倍の接眼レンズと15倍の対物レンズを使った場合、観察する倍率は何倍になるか。',
    a: '150倍',
    b: '75倍',
    c: '25倍',
    d: '12.5倍',
    explanation: '観察倍率はそれぞれのレンズの倍率をかけたものになります。',
  },
  {
    check: 'G1_ryuge_SI',
    question: 'スケッチをするときの注意点として正しくないものはどれか。',
    a: 'わかりやすいように色を塗る',
    b: '二度書きしない',
    c: '影はつけない',
    d: 'わかりやいように細い線で描く',
    explanation: '',
  },

  // 中１ 龍華 社会

  //// 中１ 大正
  // 中１ 大正 英語
  {
    check: 'G1_taisho_E',
    question:'「私は学生ではありません」正しい英文はどれか',
    a:'I am not a student.',
    b:'I am a student.',
    c:'I is not a student.',
    d:'I are not a student.',
    explanation:'否定文の文章ではis/am/areの後ろにnotを付ける',
  },
  {
    check: 'G1_taisho_E',
    question:'「水曜日」はどれか',
    a:'Wednesday',
    b:'Thursday',
    c:'Saturday',
    d:'Monday',
    explanation:'Thursday「木曜日」・Saturday「土曜日」・Monday「月曜日」',
  },
  {
    check: 'G1_taisho_E',
    question:'「１２月」はどれか',
    a:'December',
    b:'June',
    c:'January',
    d:'Novemver',
    explanation:'June「６月」・January「１月」・Novemver「１１月」',
  },
  {
    check: 'G1_taisho_E',
    question:'「２月」はどれか',
    a:'February',
    b:'August',
    c:'October',
    d:'May',
    explanation:'August「８月」・October「１０月」・May「５月」',
  },
  {
    check: 'G1_taisho_E',
    question:'Are you a tennis player?（Yesで答える）',
    a:"Yes,I am.",
    b:"Yes,I do",
    c:"No,I'm not.",
    d:"No,I don't.",
    explanation:"Are you～？で聞かれたら「Yes,I am」か「No,I'm not」で答える",
  },
  {
    check: 'G1_taisho_E',
    question:'Do you like a grape?（Noで答える）',
    a:"No,I don't.",
    b:"Yes,I am.",
    c:"No,I'm not.",
    d:"Yes,I do.",
    explanation:"Do you～?で聞かれたら「Yes,I do」か「No,I don't」で答える",
  },
  {
    check: 'G1_taisho_E',
    question:'「３月」はどれか',
    a:'March',
    b:'April',
    c:'July',
    d:'September',
    explanation:'April「４月」・July「７月」・September「９月」',
  },
  {
    check: 'G1_taisho_E',
    question:'「冬」はどれか',
    a:'winter',
    b:'spring',
    c:'fall',
    d:'summer',
    explanation:'spring「春」・summer「夏」・fall(autumn)「秋」',
  },
  // 中１ 大正 数学
  {
    check: 'G1_taisho_M',
    question: '500円の利益を「＋500」と表すとき、「－300」は何を表している？',
    a: '300円の損失',
    b: '300円の利益',
    c: '－300円の損失',
    d: '－300円の値段',
    explanation: '答え：300円の損失',
  },
  {
    check: 'G1_taisho_M',    
    question: '絶対値が4より小さい整数はいくつある？',
    a: '7個',
    b: '9個',
    c: '4個',
    d: '8個',
    explanation: '答え：7個\n －3，－2，－1，0，1，2，3の7個ですね。\n負の数が含まれることや、「より小さい」という言葉の意味に注意しましょう。',
  },
  {
    check: 'G1_taisho_M',
    question: '絶対値が等しい2つの数があり、その差が6であるとき、\nこの2つの数のうち、小さい方の数はいくつ？',
    a: '－3',
    b: '＋3',
    c: '－6',
    d: '＋6',
    explanation: '答え：－3\n 0をはさんで両側に6離れているわけですから、\n 2つの数の正体は＋3と－3ですね。',
  },
  {
    check: 'G1_taisho_M',
    question: '3－（－5）＝？',
    a: '8',
    b: '－2',
    c: '2',
    d: '－13',
    explanation: '答え：8\n間違えた人は計算問題をしっかり復習しましょう！',
  },
  {
    check: 'G1_taisho_M',
    question: '平均点より5点上であることの成績を「＋5点」を表すとき、\n 68点を取ったA君の成績は「－7点」でした。\nこのとき成績が「＋4点」だったB君の点数は何点？',
    a: '79点',
    b: '75点',
    c: '71点',
    d: '57点',
    explanation: '答え：79点\n A君が68点で「－7点」なので平均点は75点、\n B君は「＋4点」なので75＋4＝79ですね。',
  },
  {
    check: 'G1_taisho_M',    
    question: '（－6）×（－2）＝？',
    a: '12',
    b: '－12',
    c: '－3',
    d: '3',
    explanation: '答え：12\n間違えた人は計算問題をしっかり復習しましょう！',
  },
  {
    check: 'G1_taisho_M',
    question: '(－2²)と(－2)²はどちらが大きい？',
    a: '(－2)²',
    b: '(－2²)',
    c: '同じ大きさ',
    d: 'これだけでは決まらない',
    explanation: '答え：(－2)²\n(－2²)＝－2×2＝－4\n(－2)²＝(－2)×(－2)＝4になります。',
  },
  {
    check: 'G1_taisho_M',
    question: '20.23×51.84＋48.16×20.23＝？',
    a: '2023',
    b: '2097.4464',
    c: '1948.5536',
    d: '3141.5926',
    explanation: '答え：2023\n分配法則を使えば暗算でもできますね！',
  },

  // 中１ 大正 理科
  {
    check: 'G1_taisho_SI',
    question: '次のうち自ら動き回る生物はどれか。',
    a: 'アメーバ',
    b: 'ミカヅキモ',
    c: 'アオミドロ',
    d: 'ボルボックス',
    explanation: 'アメーバ以外の生物は日光の力をかりて、自ら養分をつくる「光合成」というはたらきをします。',
  },
  {
    check: 'G1_taisho_SI',
    question: 'ルーペを使うとき、見てはいけないものは何か。',
    a: '太陽',
    b: '人',
    c: '虫',
    d: '動物',
    explanation: '',
  },
  {
    check: 'G1_taisho_SI',
    question: '顕微鏡を使うとき、最初に取り付けるものは何か。',
    a: '接眼レンズ',
    b: '対物レンズ',
    c: 'レボルバー',
    d: '反射鏡',
    explanation: '',
  },
  {
    check: 'G1_taisho_SI',
    question: '顕微鏡で観察したとき、観察したいものが左下に見えた。視野の中央に移動させるには、プレパラートをどの方向に動かせばよいか。',
    a: '左下',
    b: '右下',
    c: '左上',
    d: '右上',
    explanation: '顕微鏡では左右上下逆に見えます。',
  },
  {
    check: 'G1_taisho_SI',
    question: '顕微鏡で観察をするとき、レンズを付けた後にすることは何か。',
    a: '反射鏡としぼりで視野の明るさを調整する。',
    b: '対物レンズとプレパラートの距離をできるだけ近づける。',
    c: 'レボルバーを回し、高倍率の対物レンズにする。',
    d: '調節ねじでピントを合わせる',
    explanation: '',
  },
  {
    check: 'G1_taisho_SI',
    question: 'めしべの先端の部分を何というか。',
    a: '柱頭',
    b: 'やく',
    c: 'がく',
    d: '子房',
    explanation: '',
  },
  {
    check: 'G1_taisho_SI',
    question: 'おしべの先端にあるやくには何が入っているか。',
    a: '花粉',
    b: '胚珠',
    c: '種子',
    d: '子房',
    explanation: '',
  },
  {
    check: 'G1_taisho_SI',
    question: '20～40倍程度に拡大でき、物体を立体的にみることができる顕微鏡を何というか。',
    a: '双眼実体顕微鏡',
    b: '金属顕微鏡',
    c: '生物顕微鏡',
    d: 'デジタル顕微鏡',
    explanation: '双眼実体顕微鏡は物体の向きはそのままで、立体的にみることができます。',
  },
  {
    check: 'G1_taisho_SI',
    question: '10倍の接眼レンズと15倍の対物レンズを使った場合、観察する倍率は何倍になるか。',
    a: '150倍',
    b: '75倍',
    c: '25倍',
    d: '12.5倍',
    explanation: '観察倍率はそれぞれのレンズの倍率をかけたものになります。',
  },
  {
    check: 'G1_taisho_SI',
    question: 'スケッチをするときの注意点として正しくないものはどれか。',
    a: 'わかりやすいように色を塗る',
    b: '二度書きしない',
    c: '影はつけない',
    d: 'わかりやいように細い線で描く',
    explanation: '',
  },

  // 中１ 大正 社会

  //// 中１ 曙川南
  // 中１ 曙川南 英語
  {
    check: 'G1_akenan_E',
    question:'「私は学生ではありません」正しい英文はどれか',
    a:'I am not a student.',
    b:'I am a student.',
    c:'I is not a student.',
    d:'I are not a student.',
    explanation:'否定文の文章ではis/am/areの後ろにnotを付ける',
  },
  {
    check: 'G1_akenan_E',
    question:'「水曜日」はどれか',
    a:'Wednesday',
    b:'Thursday',
    c:'Saturday',
    d:'Monday',
    explanation:'Thursday「木曜日」・Saturday「土曜日」・Monday「月曜日」',
  },
  {
    check: 'G1_akenan_E',
    question:'「１２月」はどれか',
    a:'December',
    b:'June',
    c:'January',
    d:'Novemver',
    explanation:'June「６月」・January「１月」・Novemver「１１月」',
  },
  {
    check: 'G1_akenan_E',
    question:'「２月」はどれか',
    a:'February',
    b:'August',
    c:'October',
    d:'May',
    explanation:'August「８月」・October「１０月」・May「５月」',
  },
  {
    check: 'G1_akenan_E',
    question:'Are you a tennis player?（Yesで答える）',
    a:"Yes,I am.",
    b:"Yes,I do",
    c:"No,I'm not.",
    d:"No,I don't.",
    explanation:"Are you～？で聞かれたら「Yes,I am」か「No,I'm not」で答える",
  },
  {
    check: 'G1_akenan_E',
    question:'Do you like a grape?（Noで答える）',
    a:"No,I don't.",
    b:"Yes,I am.",
    c:"No,I'm not.",
    d:"Yes,I do.",
    explanation:"Do you～?で聞かれたら「Yes,I do」か「No,I don't」で答える",
  },
  {
    check: 'G1_akenan_E',
    question:'「３月」はどれか',
    a:'March',
    b:'April',
    c:'July',
    d:'September',
    explanation:'April「４月」・July「７月」・September「９月」',
  },
  {
    check: 'G1_akenan_E',
    question:'「冬」はどれか',
    a:'winter',
    b:'spring',
    c:'fall',
    d:'summer',
    explanation:'spring「春」・summer「夏」・fall(autumn)「秋」',
  },
  // 中１ 曙川南 数学
  {
    check: 'G1_akenan_M',
    question: '500円の利益を「＋500」と表すとき、「－300」は何を表している？',
    a: '300円の損失',
    b: '300円の利益',
    c: '－300円の損失',
    d: '－300円の値段',
    explanation: '答え：300円の損失',
  },
  {
    check: 'G1_akenan_M',    
    question: '絶対値が4より小さい整数はいくつある？',
    a: '7個',
    b: '9個',
    c: '4個',
    d: '8個',
    explanation: '答え：7個\n －3，－2，－1，0，1，2，3の7個ですね。\n負の数が含まれることや、「より小さい」という言葉の意味に注意しましょう。',
  },
  {
    check: 'G1_akenan_M',
    question: '絶対値が等しい2つの数があり、その差が6であるとき、\nこの2つの数のうち、小さい方の数はいくつ？',
    a: '－3',
    b: '＋3',
    c: '－6',
    d: '＋6',
    explanation: '答え：－3\n 0をはさんで両側に6離れているわけですから、\n 2つの数の正体は＋3と－3ですね。',
  },
  {
    check: 'G1_akenan_M',
    question: '3－（－5）＝？',
    a: '8',
    b: '－2',
    c: '2',
    d: '－13',
    explanation: '答え：8\n間違えた人は計算問題をしっかり復習しましょう！',
  },
  {
    check: 'G1_akenan_M',
    question: '平均点より5点上であることの成績を「＋5点」を表すとき、\n 68点を取ったA君の成績は「－7点」でした。\nこのとき成績が「＋4点」だったB君の点数は何点？',
    a: '79点',
    b: '75点',
    c: '71点',
    d: '57点',
    explanation: '答え：79点\n A君が68点で「－7点」なので平均点は75点、\n B君は「＋4点」なので75＋4＝79ですね。',
  },
  {
    check: 'G1_akenan_M',    
    question: '（－6）×（－2）＝？',
    a: '12',
    b: '－12',
    c: '－3',
    d: '3',
    explanation: '答え：12\n間違えた人は計算問題をしっかり復習しましょう！',
  },
  {
    check: 'G1_akenan_M',
    question: '(－2²)と(－2)²はどちらが大きい？',
    a: '(－2)²',
    b: '(－2²)',
    c: '同じ大きさ',
    d: 'これだけでは決まらない',
    explanation: '答え：(－2)²\n(－2²)＝－2×2＝－4\n(－2)²＝(－2)×(－2)＝4になります。',
  },
  {
    check: 'G1_akenan_M',
    question: '20.23×51.84＋48.16×20.23＝？',
    a: '2023',
    b: '2097.4464',
    c: '1948.5536',
    d: '3141.5926',
    explanation: '答え：2023\n分配法則を使えば暗算でもできますね！',
  },

  // 中１ 曙川南 理科
  {
    check: 'G1_akenan_SI',
    question: '次のうち自ら動き回る生物はどれか。',
    a: 'アメーバ',
    b: 'ミカヅキモ',
    c: 'アオミドロ',
    d: 'ボルボックス',
    explanation: 'アメーバ以外の生物は日光の力をかりて、自ら養分をつくる「光合成」というはたらきをします。',
  },
  {
    check: 'G1_akenan_SI',
    question: 'ルーペを使うとき、見てはいけないものは何か。',
    a: '太陽',
    b: '人',
    c: '虫',
    d: '動物',
    explanation: '',
  },
  {
    check: 'G1_akenan_SI',
    question: '顕微鏡を使うとき、最初に取り付けるものは何か。',
    a: '接眼レンズ',
    b: '対物レンズ',
    c: 'レボルバー',
    d: '反射鏡',
    explanation: '',
  },
  {
    check: 'G1_akenan_SI',
    question: '顕微鏡で観察したとき、観察したいものが左下に見えた。視野の中央に移動させるには、プレパラートをどの方向に動かせばよいか。',
    a: '左下',
    b: '右下',
    c: '左上',
    d: '右上',
    explanation: '顕微鏡では左右上下逆に見えます。',
  },
  {
    check: 'G1_akenan_SI',
    question: '顕微鏡で観察をするとき、レンズを付けた後にすることは何か。',
    a: '反射鏡としぼりで視野の明るさを調整する。',
    b: '対物レンズとプレパラートの距離をできるだけ近づける。',
    c: 'レボルバーを回し、高倍率の対物レンズにする。',
    d: '調節ねじでピントを合わせる',
    explanation: '',
  },
  {
    check: 'G1_akenan_SI',
    question: 'めしべの先端の部分を何というか。',
    a: '柱頭',
    b: 'やく',
    c: 'がく',
    d: '子房',
    explanation: '',
  },
  {
    check: 'G1_akenan_SI',
    question: 'おしべの先端にあるやくには何が入っているか。',
    a: '花粉',
    b: '胚珠',
    c: '種子',
    d: '子房',
    explanation: '',
  },
  {
    check: 'G1_akenan_SI',
    question: '20～40倍程度に拡大でき、物体を立体的にみることができる顕微鏡を何というか。',
    a: '双眼実体顕微鏡',
    b: '金属顕微鏡',
    c: '生物顕微鏡',
    d: 'デジタル顕微鏡',
    explanation: '双眼実体顕微鏡は物体の向きはそのままで、立体的にみることができます。',
  },
  {
    check: 'G1_akenan_SI',
    question: '10倍の接眼レンズと15倍の対物レンズを使った場合、観察する倍率は何倍になるか。',
    a: '150倍',
    b: '75倍',
    c: '25倍',
    d: '12.5倍',
    explanation: '観察倍率はそれぞれのレンズの倍率をかけたものになります。',
  },
  {
    check: 'G1_akenan_SI',
    question: 'スケッチをするときの注意点として正しくないものはどれか。',
    a: 'わかりやすいように色を塗る',
    b: '二度書きしない',
    c: '影はつけない',
    d: 'わかりやいように細い線で描く',
    explanation: '',
  },

  // 中１ 曙川南 社会

  //// 中１ 南高安
  // 中１ 南高安 英語
  {
    check: 'G1_nantaka_E',
    question:'「私は学生ではありません」正しい英文はどれか',
    a:'I am not a student.',
    b:'I am a student.',
    c:'I is not a student.',
    d:'I are not a student.',
    explanation:'否定文の文章ではis/am/areの後ろにnotを付ける',
  },
  {
    check: 'G1_nantaka_E',
    question:'「水曜日」はどれか',
    a:'Wednesday',
    b:'Thursday',
    c:'Saturday',
    d:'Monday',
    explanation:'Thursday「木曜日」・Saturday「土曜日」・Monday「月曜日」',
  },
  {
    check: 'G1_nantaka_E',
    question:'「１２月」はどれか',
    a:'December',
    b:'June',
    c:'January',
    d:'Novemver',
    explanation:'June「６月」・January「１月」・Novemver「１１月」',
  },
  {
    check: 'G1_nantaka_E',
    question:'「２月」はどれか',
    a:'February',
    b:'August',
    c:'October',
    d:'May',
    explanation:'August「８月」・October「１０月」・May「５月」',
  },
  {
    check: 'G1_nantaka_E',
    question:'Are you a tennis player?（Yesで答える）',
    a:"Yes,I am.",
    b:"Yes,I do",
    c:"No,I'm not.",
    d:"No,I don't.",
    explanation:"Are you～？で聞かれたら「Yes,I am」か「No,I'm not」で答える",
  },
  {
    check: 'G1_nantaka_E',
    question:'Do you like a grape?（Noで答える）',
    a:"No,I don't.",
    b:"Yes,I am.",
    c:"No,I'm not.",
    d:"Yes,I do.",
    explanation:"Do you～?で聞かれたら「Yes,I do」か「No,I don't」で答える",
  },
  {
    check: 'G1_nantaka_E',
    question:'「３月」はどれか',
    a:'March',
    b:'April',
    c:'July',
    d:'September',
    explanation:'April「４月」・July「７月」・September「９月」',
  },
  {
    check: 'G1_nantaka_E',
    question:'「冬」はどれか',
    a:'winter',
    b:'spring',
    c:'fall',
    d:'summer',
    explanation:'spring「春」・summer「夏」・fall(autumn)「秋」',
  },
  // 中１ 南高安 数学
  {
    check: 'G1_nantaka_M',
    question: '500円の利益を「＋500」と表すとき、「－300」は何を表している？',
    a: '300円の損失',
    b: '300円の利益',
    c: '－300円の損失',
    d: '－300円の値段',
    explanation: '答え：300円の損失',
  },
  {
    check: 'G1_nantaka_M',    
    question: '絶対値が4より小さい整数はいくつある？',
    a: '7個',
    b: '9個',
    c: '4個',
    d: '8個',
    explanation: '答え：7個\n －3，－2，－1，0，1，2，3の7個ですね。\n負の数が含まれることや、「より小さい」という言葉の意味に注意しましょう。',
  },
  {
    check: 'G1_nantaka_M',
    question: '絶対値が等しい2つの数があり、その差が6であるとき、\nこの2つの数のうち、小さい方の数はいくつ？',
    a: '－3',
    b: '＋3',
    c: '－6',
    d: '＋6',
    explanation: '答え：－3\n 0をはさんで両側に6離れているわけですから、\n 2つの数の正体は＋3と－3ですね。',
  },
  {
    check: 'G1_nantaka_M',
    question: '3－（－5）＝？',
    a: '8',
    b: '－2',
    c: '2',
    d: '－13',
    explanation: '答え：8\n間違えた人は計算問題をしっかり復習しましょう！',
  },
  {
    check: 'G1_nantaka_M',
    question: '平均点より5点上であることの成績を「＋5点」を表すとき、\n 68点を取ったA君の成績は「－7点」でした。\nこのとき成績が「＋4点」だったB君の点数は何点？',
    a: '79点',
    b: '75点',
    c: '71点',
    d: '57点',
    explanation: '答え：79点\n A君が68点で「－7点」なので平均点は75点、\n B君は「＋4点」なので75＋4＝79ですね。',
  },

  // 中１ 南高安 理科
  {
    check: 'G1_nantaka_SI',
    question: '次のうち自ら動き回る生物はどれか。',
    a: 'アメーバ',
    b: 'ミカヅキモ',
    c: 'アオミドロ',
    d: 'ボルボックス',
    explanation: 'アメーバ以外の生物は日光の力をかりて、自ら養分をつくる「光合成」というはたらきをします。',
  },
  {
    check: 'G1_nantaka_SI',
    question: 'ルーペを使うとき、見てはいけないものは何か。',
    a: '太陽',
    b: '人',
    c: '虫',
    d: '動物',
    explanation: '',
  },
  {
    check: 'G1_nantaka_SI',
    question: '顕微鏡を使うとき、最初に取り付けるものは何か。',
    a: '接眼レンズ',
    b: '対物レンズ',
    c: 'レボルバー',
    d: '反射鏡',
    explanation: '',
  },
  {
    check: 'G1_nantaka_SI',
    question: '顕微鏡で観察したとき、観察したいものが左下に見えた。視野の中央に移動させるには、プレパラートをどの方向に動かせばよいか。',
    a: '左下',
    b: '右下',
    c: '左上',
    d: '右上',
    explanation: '顕微鏡では左右上下逆に見えます。',
  },
  {
    check: 'G1_nantaka_SI',
    question: '顕微鏡で観察をするとき、レンズを付けた後にすることは何か。',
    a: '反射鏡としぼりで視野の明るさを調整する。',
    b: '対物レンズとプレパラートの距離をできるだけ近づける。',
    c: 'レボルバーを回し、高倍率の対物レンズにする。',
    d: '調節ねじでピントを合わせる',
    explanation: '',
  },
  {
    check: 'G1_nantaka_SI',
    question: 'めしべの先端の部分を何というか。',
    a: '柱頭',
    b: 'やく',
    c: 'がく',
    d: '子房',
    explanation: '',
  },
  {
    check: 'G1_nantaka_SI',
    question: 'おしべの先端にあるやくには何が入っているか。',
    a: '花粉',
    b: '胚珠',
    c: '種子',
    d: '子房',
    explanation: '',
  },
  {
    check: 'G1_nantaka_SI',
    question: '20～40倍程度に拡大でき、物体を立体的にみることができる顕微鏡を何というか。',
    a: '双眼実体顕微鏡',
    b: '金属顕微鏡',
    c: '生物顕微鏡',
    d: 'デジタル顕微鏡',
    explanation: '双眼実体顕微鏡は物体の向きはそのままで、立体的にみることができます。',
  },
  {
    check: 'G1_nantaka_SI',
    question: '10倍の接眼レンズと15倍の対物レンズを使った場合、観察する倍率は何倍になるか。',
    a: '150倍',
    b: '75倍',
    c: '25倍',
    d: '12.5倍',
    explanation: '観察倍率はそれぞれのレンズの倍率をかけたものになります。',
  },
  {
    check: 'G1_nantaka_SI',
    question: 'スケッチをするときの注意点として正しくないものはどれか。',
    a: 'わかりやすいように色を塗る',
    b: '二度書きしない',
    c: '影はつけない',
    d: 'わかりやいように細い線で描く',
    explanation: '',
  },
  // 中１ 南高安 社会



  ////// 中２
  //// 中２ 亀井
  // 中２ 亀井 英語
  {
    check: 'G2_kamei_E',
    question:'When I go to school,I take a bus.と同じ意味の英文はどれか',
    a:'I take a bus when I go to school.',
    b:'I take a bus,when I go to school.',
    c:'When I take a bus, I go to school.',
    d:'I go to school when I take a bus.',
    explanation:'When～,はコンマ無しで文末に置く事ができる',
  },
  {
    check: 'G2_kamei_E',
    question:'「私が家に帰ってきた時、父はテレビを見ていました」の意味の英文はどれか',
    a:'When I came home,my father was waching TV.',
    b:'When I came home,my father watched TV.',
    c:'When I was coming home,my father was watching TV.',
    d:'When I came home,my father is watching TV.',
    explanation:'時制の一致なのでwhenのカタマリも過去形にする',
  },
  {
    check: 'G2_kamei_E',    
    question:'「もし明日晴れたら、野球をするつもりです」の意味の英文はどれか',
    a:'If it is sunny tomorrow,I will play baseball.',
    b:'If it will be sunny tomorrow,I will play baseball.',
    c:'If it is sunny tomorrow,I play baseball.',
    d:'If it will be sunny tomorrow,I play baseball.',
    explanation:'tomorrowなど未来を表す単語があっても、Ifの中は現在形にする。',
  },
  {
    check: 'G2_kamei_E',    
    question:'I think（　　）the book is interesting.（　）に入る単語はどれか',
    a:'that',
    b:'and',
    c:'when',
    d:'if',
    explanation:'接続詞のthatは省略可能',
  },
  {
    check: 'G2_kamei_E',    
    question:'I want to buy a car.の正しい日本語訳はどれか',
    a:'私は車を買いたい。',
    b:'私は車を買ってほしい。',
    c:'私は車を買ってあげて欲しい。',
    d:'私は車を買いたかった。',
    explanation:'want to～は名詞的用法だが「～したい」という訳になる',
  },
  {
    check: 'G2_kamei_E',    
    question:'My dream is to be a teacher.この文のtoの用法はどれか',
    a:'名詞的用法',
    b:'形容詞的用法',
    c:'副詞的用法',
    d:'前置詞的用法',
    explanation:'動詞の真後ろ（右隣）にtoがあるので「～すること」の名詞的用法を選ぶ',
  },
  {
    check: 'G2_kamei_E',    
    question:'To play tennis,Tom went to the park.この文のtoの用法はどれか',
    a:'副詞的用法',
    b:'形容詞的用法',
    c:'名詞的用法',
    d:'前置詞的用法',
    explanation:'To～,で始まる不定詞の用法は絶対に「～するために」の副詞的用法',
  },
  {
    check: 'G2_kamei_E',    
    question:'She has something to eat.この文のtoの用法はどれか',
    a:'形容詞的用法',
    b:'名詞的用法',
    c:'副詞的用法',
    d:'前置詞的用法',
    explanation:'名詞の真後ろ（右隣）にtoがあれば形容詞的用法の可能性は高く、somethingが使われていれば形容詞的用法になる',
  },
  {
    check: 'G2_kamei_E',    
    question:'I went to the library to do my homework.',
    a:'副詞的用法',
    b:'形容詞的用法',
    c:'名詞的用法',
    d:'前置詞的用法',
    explanation:'宿題をするためにと「理由」を述べているので「～するために」の副詞的用法を選ぶ',    
  },    
  // 中２ 亀井 数学
  {
    check: 'G2_kamei_M',
    question: '次の式の次数を答えなさい。\n3x²＋4x－1',
    a: '2',
    b: '3',
    c: '4',
    d: '－1',
    explanation: '答え：2\n項ごとにわけて文字の数を数えましょう。\nx²があるので2ですね。',
  },
  {
    check: 'G2_kamei_M',
    question: '次の式は何次式ですか。\na²＋b²＋c²－6abc',
    a: '3次式',
    b: '2次式',
    c: '9次式',
    d: '6次式',
    explanation: '答え：3次式\n項ごとにわけて文字の数を数えましょう。\nabcがあるので3次式ですね。',
  },
  {
    check: 'G2_kamei_M',
    question: '百の位の数がa、十の位の数がb、一の位の数がcである3けたの整数を正しく表したものはどれ？',
    a: '100a＋10b＋c',
    b: 'a＋b＋c',
    c: 'abc',
    d: '他のどの選択肢も間違っている',
    explanation: '答え：100a+10b+c\n〇の位の数というのは、〇がいくつ分かを表します。\n百の位の数がaなら100がa個分、すなわち100aです。',
  },
  {
    check: 'G2_kamei_M',
    question: '次の式の各項の係数として、正しくないものはどれ？\nx³－2x²－x',
    a: '2',
    b: '－1',
    c: '1',
    d: '－2',
    explanation: '答え：2\nx³の係数は1、－2x²の係数は－2、－xの係数は－1ですね。\n－も含まれることに注意しましょう。',
  },
  {
    check: 'G2_kamei_M',
    question: '次の式について述べた文章のうち、正しくないものはどれ？\ 8x－8y＋8',
    a: 'xについて解くとx＝y－1となる',
    b: '1次式である',
    c: '8(x－y＋1) と等しい',
    d: 'x＝1，y＝－1のときの値は24である',
    explanation: '答え：xについて解くとx＝y－1となる\n〇〇について解けるのは「方程式」です。\nこの式には「＝」が含まれないため方程式ではありません。',
  },

  // 中２ 亀井 理科
  {
    check: 'G2_kamei_SI',
    question: '体が多くの細胞で出来ている生物を何といいますか。',
    a: '多細胞生物',
    b: '単細胞生物',
    c: '組織',
    d: '個体',
    explanation: '単細胞生物は１つの細胞が生きるための全てのはたらきをします。',
  },
  {
    check: 'G2_kamei_SI',
    question: '動物の細胞にしか存在しないものとして適切ではないものは次のうちどれか。',
    a: '液胞',
    b: '細胞膜',
    c: '核',
    d: '細胞質',
    explanation: '植物細胞にしか存在しないものとして、液胞(細胞の活動によりできた物質が溶けた液で満たされたもの)・細胞壁(植物のからだを支えたり、守ったりするもの)・葉緑体(光合成をするもの)があります。',
  },
  {
    check: 'G2_kamei_SI',
    question: '根で吸収した水や水に溶けた養分が通る管を何というか。',
    a: '道管',
    b: '師管',
    c: '維管束',
    d: '葉脈',
    explanation: 'ウチの上水道管(茎で内側、葉で上側を通り水が通る道管)で覚えましょう。',
  },
  {
    check: 'G2_kamei_SI',
    question: '維管束が輪のように並ぶ植物は何でしょう。',
    a: '双子葉類',
    b: '単子葉類',
    c: 'シダ植物',
    d: 'コケ植物',
    explanation: '単子葉類は維管束がバラバラに存在します。',
  },
  {
    check: 'G2_kamei_SI',
    question: '光合成に必要なものとして適切ではないものはどれか。',
    a: 'デンプン',
    b: '二酸化炭素',
    c: '水',
    d: '光',
    explanation: '光合成は、二酸化炭素と水を材料とし、光エネルギーをつかって、葉緑体で酸素とデンプンを作り出します。',
  },
  {
    check: 'G2_kamei_SI',
    question: '消化液に含まれる、養分を分解するはたらきのある物質を何というか。',
    a: '消化酵素',
    b: '消化液',
    c: '消化管',
    d: '肺胞',
    explanation: '消化酵素の中には、だ液に含まれるアミラーゼ・胃液に含まれるペプシン、すい液に含まれるリパーゼなどがあります。',
  },
  {
    check: 'G2_kamei_SI',
    question: 'デンプンにはたらく消化液として適当でないものはどれか。',
    a: '胃液',
    b: 'だ液',
    c: 'すい液',
    d: '腸液',
    explanation: '',
  },
  {
    check: 'G2_kamei_SI',
    question: '次のうち消化酵素をもたない消化液はどれか。',
    a: '胆汁',
    b: '腸液',
    c: '胃液',
    d: 'だ液',
    explanation: '胆汁は消化酵素を持ちませんが、脂肪の分解を助けるはたらきをもちます。',
  },
  {
    check: 'G2_kamei_SI',
    question: 'デンプンは分解され、最終的になんという物質になるか。',
    a: 'ブドウ糖',
    b: 'アミノ酸',
    c: '脂肪酸',
    d: 'モノグリセリド',
    explanation: '',
  },
  {
    check: 'G2_kamei_SI',
    question: 'タンパク質は分解され、最終的になんという物質になるか。',
    a: 'アミノ酸',
    b: 'ブドウ糖',
    c: '脂肪酸',
    d: 'モノグリセリド',
    explanation: '',
  },
  {
    check: 'G2_kamei_SI',
    question: '脂肪は小腸に吸収されたあと、何という管に入るか。',
    a: 'リンパ管',
    b: '毛細血管',
    c: '道管',
    d: '師管',
    explanation: 'ブドウ糖とアミノ酸は毛細血管に入ります。',
  },
  {
    check: 'G2_kamei_SI',
    question: '息を吸うときの説明として正しいものはどれか。',
    a: 'ろっ骨が上がり、横隔膜が下がる',
    b: 'ろっ骨が上がり、横隔膜が上がる',
    c: 'ろっ骨が下がり、横隔膜が下がる',
    d: 'ろっ骨が下がり、横隔膜が上がる',
    explanation: '息を吸うときは胸腔を広くし、息を吐くときは胸腔を狭くするために、ろっ骨が下がり、横隔膜が上がります。',
  },
  {
    check: 'G2_kamei_SI',
    question: '血液の成分のうち、酸素の運搬をするものは次のうちどれか。',
    a: '赤血球',
    b: '白血球',
    c: '血小板',
    d: '血しょう',
    explanation: '赤血球は酸素の多いところでは酸素と結合し、酸素の少ないところでは酸素を手放す性質をもちます。',
  },
  {
    check: 'G2_kamei_SI',
    question: '血液の成分のうち、病原体を分解するものは次のうちどれか。',
    a: '白血球',
    b: '赤血球',
    c: '血小板',
    d: '血しょう',
    explanation: '白血球は病原体を食べて殺す性質をもちます。',
  },
  {
    check: 'G2_kamei_SI',
    question: '血液の成分のうち、血をかためるものは次のうちどれか。',
    a: '血小板',
    b: '赤血球',
    c: '白血球',
    d: '血しょう',
    explanation: '血小板は血をかためてかさぶたを作る性質をもちます。',
  },
  {
    check: 'G2_kamei_SI',
    question: '赤血球に含まれるヘモグロビンは何色の色素成分でしょう。',
    a: '赤色',
    b: '黄色',
    c: '無色透明',
    d: '緑色',
    explanation: '',
  },
  // 中２ 亀井 社会

  //// 中２ 龍華
  // 中２ 龍華 英語
  {
    check: 'G2_ryuge_E',
    question:'When I go to school,I take a bus.と同じ意味の英文はどれか',
    a:'I take a bus when I go to school.',
    b:'I take a bus,when I go to school.',
    c:'When I take a bus, I go to school.',
    d:'I go to school when I take a bus.',
    explanation:'When～,はコンマ無しで文末に置く事ができる',
  },
  {
    check: 'G2_ryuge_E',
    question:'「私が家に帰ってきた時、父はテレビを見ていました」の意味の英文はどれか',
    a:'When I came home,my father was waching TV.',
    b:'When I came home,my father watched TV.',
    c:'When I was coming home,my father was watching TV.',
    d:'When I came home,my father is watching TV.',
    explanation:'時制の一致なのでwhenのカタマリも過去形にする',
  },
  {
    check: 'G2_ryuge_E',    
    question:'「もし明日晴れたら、野球をするつもりです」の意味の英文はどれか',
    a:'If it is sunny tomorrow,I will play baseball.',
    b:'If it will be sunny tomorrow,I will play baseball.',
    c:'If it is sunny tomorrow,I play baseball.',
    d:'If it will be sunny tomorrow,I play baseball.',
    explanation:'tomorrowなど未来を表す単語があっても、Ifの中は現在形にする。',
  },
  {
    check: 'G2_ryuge_E',    
    question:'I think（　　）the book is interesting.（　）に入る単語はどれか',
    a:'that',
    b:'and',
    c:'when',
    d:'if',
    explanation:'接続詞のthatは省略可能',
  },    
    

  // 中２ 龍華 数学
  {
    check: 'G2_ryuge_M',
    question: '次の式の次数を答えなさい。\n3x²＋4x－1',
    a: '2',
    b: '3',
    c: '4',
    d: '－1',
    explanation: '答え：2\n項ごとにわけて文字の数を数えましょう。\nx²があるので2ですね。',
  },
  {
    check: 'G2_ryuge_M',
    question: '次の式は何次式ですか。\na²＋b²＋c²－6abc',
    a: '3次式',
    b: '2次式',
    c: '9次式',
    d: '6次式',
    explanation: '答え：3次式\n項ごとにわけて文字の数を数えましょう。\nabcがあるので3次式ですね。',
  },
  {
    check: 'G2_ryuge_M',
    question: '百の位の数がa、十の位の数がb、一の位の数がcである3けたの整数を正しく表したものはどれ？',
    a: '100a＋10b＋c',
    b: 'a＋b＋c',
    c: 'abc',
    d: '他のどの選択肢も間違っている',
    explanation: '答え：100a+10b+c\n〇の位の数というのは、〇がいくつ分かを表します。\n百の位の数がaなら100がa個分、すなわち100aです。',
  },
  {
    check: 'G2_ryuge_M',
    question: '次の式の各項の係数として、正しくないものはどれ？\nx³－2x²－x',
    a: '2',
    b: '－1',
    c: '1',
    d: '－2',
    explanation: '答え：2\nx³の係数は1、－2x²の係数は－2、－xの係数は－1ですね。\n－も含まれることに注意しましょう。',
  },
  {
    check: 'G2_ryuge_M',
    question: '次の式について述べた文章のうち、正しくないものはどれ？\ 8x－8y＋8',
    a: 'xについて解くとx＝y－1となる',
    b: '1次式である',
    c: '8(x－y＋1) と等しい',
    d: 'x＝1，y＝－1のときの値は24である',
    explanation: '答え：xについて解くとx＝y－1となる\n〇〇について解けるのは「方程式」です。\nこの式には「＝」が含まれないため方程式ではありません。',
  },

  // 中２ 龍華 理科
  {
    check: 'G2_ryuge_SI',
    question: '体が多くの細胞で出来ている生物を何といいますか。',
    a: '多細胞生物',
    b: '単細胞生物',
    c: '組織',
    d: '個体',
    explanation: '単細胞生物は１つの細胞が生きるための全てのはたらきをします。',
  },
  {
    check: 'G2_ryuge_SI',
    question: '動物の細胞にしか存在しないものとして適切ではないものは次のうちどれか。',
    a: '液胞',
    b: '細胞膜',
    c: '核',
    d: '細胞質',
    explanation: '植物細胞にしか存在しないものとして、液胞(細胞の活動によりできた物質が溶けた液で満たされたもの)・細胞壁(植物のからだを支えたり、守ったりするもの)・葉緑体(光合成をするもの)があります。',
  },
  {
    check: 'G2_ryuge_SI',
    question: '根で吸収した水や水に溶けた養分が通る管を何というか。',
    a: '道管',
    b: '師管',
    c: '維管束',
    d: '葉脈',
    explanation: 'ウチの上水道管(茎で内側、葉で上側を通り水が通る道管)で覚えましょう。',
  },
  {
    check: 'G2_ryuge_SI',
    question: '維管束が輪のように並ぶ植物は何でしょう。',
    a: '双子葉類',
    b: '単子葉類',
    c: 'シダ植物',
    d: 'コケ植物',
    explanation: '単子葉類は維管束がバラバラに存在します。',
  },
  {
    check: 'G2_ryuge_SI',
    question: '光合成に必要なものとして適切ではないものはどれか。',
    a: 'デンプン',
    b: '二酸化炭素',
    c: '水',
    d: '光',
    explanation: '光合成は、二酸化炭素と水を材料とし、光エネルギーをつかって、葉緑体で酸素とデンプンを作り出します。',
  },
  {
    check: 'G2_ryuge_SI',
    question: '消化液に含まれる、養分を分解するはたらきのある物質を何というか。',
    a: '消化酵素',
    b: '消化液',
    c: '消化管',
    d: '肺胞',
    explanation: '消化酵素の中には、だ液に含まれるアミラーゼ・胃液に含まれるペプシン、すい液に含まれるリパーゼなどがあります。',
  },
  {
    check: 'G2_ryuge_SI',
    question: 'デンプンにはたらく消化液として適当でないものはどれか。',
    a: '胃液',
    b: 'だ液',
    c: 'すい液',
    d: '腸液',
    explanation: '',
  },
  {
    check: 'G2_ryuge_SI',
    question: '次のうち消化酵素をもたない消化液はどれか。',
    a: '胆汁',
    b: '腸液',
    c: '胃液',
    d: 'だ液',
    explanation: '胆汁は消化酵素を持ちませんが、脂肪の分解を助けるはたらきをもちます。',
  },
  {
    check: 'G2_ryuge_SI',
    question: 'デンプンは分解され、最終的になんという物質になるか。',
    a: 'ブドウ糖',
    b: 'アミノ酸',
    c: '脂肪酸',
    d: 'モノグリセリド',
    explanation: '',
  },
  {
    check: 'G2_ryuge_SI',
    question: 'タンパク質は分解され、最終的になんという物質になるか。',
    a: 'アミノ酸',
    b: 'ブドウ糖',
    c: '脂肪酸',
    d: 'モノグリセリド',
    explanation: '',
  },
  {
    check: 'G2_ryuge_SI',
    question: '脂肪は小腸に吸収されたあと、何という管に入るか。',
    a: 'リンパ管',
    b: '毛細血管',
    c: '道管',
    d: '師管',
    explanation: 'ブドウ糖とアミノ酸は毛細血管に入ります。',
  },
  {
    check: 'G2_ryuge_SI',
    question: '息を吸うときの説明として正しいものはどれか。',
    a: 'ろっ骨が上がり、横隔膜が下がる',
    b: 'ろっ骨が上がり、横隔膜が上がる',
    c: 'ろっ骨が下がり、横隔膜が下がる',
    d: 'ろっ骨が下がり、横隔膜が上がる',
    explanation: '息を吸うときは胸腔を広くし、息を吐くときは胸腔を狭くするために、ろっ骨が下がり、横隔膜が上がります。',
  },
  {
    check: 'G2_ryuge_SI',
    question: '血液の成分のうち、酸素の運搬をするものは次のうちどれか。',
    a: '赤血球',
    b: '白血球',
    c: '血小板',
    d: '血しょう',
    explanation: '赤血球は酸素の多いところでは酸素と結合し、酸素の少ないところでは酸素を手放す性質をもちます。',
  },
  {
    check: 'G2_ryuge_SI',
    question: '血液の成分のうち、病原体を分解するものは次のうちどれか。',
    a: '白血球',
    b: '赤血球',
    c: '血小板',
    d: '血しょう',
    explanation: '白血球は病原体を食べて殺す性質をもちます。',
  },
  {
    check: 'G2_ryuge_SI',
    question: '血液の成分のうち、血をかためるものは次のうちどれか。',
    a: '血小板',
    b: '赤血球',
    c: '白血球',
    d: '血しょう',
    explanation: '血小板は血をかためてかさぶたを作る性質をもちます。',
  },
  {
    check: 'G2_ryuge_SI',
    question: '赤血球に含まれるヘモグロビンは何色の色素成分でしょう。',
    a: '赤色',
    b: '黄色',
    c: '無色透明',
    d: '緑色',
    explanation: '',
  },
  // 中２ 龍華 社会

  //// 中２ 大正
  // 中２ 大正 英語
  {
    check: 'G2_taisho_E',
    question:'When I go to school,I take a bus.と同じ意味の英文はどれか',
    a:'I take a bus when I go to school.',
    b:'I take a bus,when I go to school.',
    c:'When I take a bus, I go to school.',
    d:'I go to school when I take a bus.',
    explanation:'When～,はコンマ無しで文末に置く事ができる',
  },
  {
    check: 'G2_taisho_E',
    question:'「私が家に帰ってきた時、父はテレビを見ていました」の意味の英文はどれか',
    a:'When I came home,my father was waching TV.',
    b:'When I came home,my father watched TV.',
    c:'When I was coming home,my father was watching TV.',
    d:'When I came home,my father is watching TV.',
    explanation:'時制の一致なのでwhenのカタマリも過去形にする',
  },
  {
    check: 'G2_taisho_E',    
    question:'「もし明日晴れたら、野球をするつもりです」の意味の英文はどれか',
    a:'If it is sunny tomorrow,I will play baseball.',
    b:'If it will be sunny tomorrow,I will play baseball.',
    c:'If it is sunny tomorrow,I play baseball.',
    d:'If it will be sunny tomorrow,I play baseball.',
    explanation:'tomorrowなど未来を表す単語があっても、Ifの中は現在形にする。',
  },
  {
    check: 'G2_taisho_E',    
    question:'I think（　　）the book is interesting.（　）に入る単語はどれか',
    a:'that',
    b:'and',
    c:'when',
    d:'if',
    explanation:'接続詞のthatは省略可能',
  },    

  // 中２ 大正 数学
  {
    check: 'G2_taisho_M',
    question: '次の式の次数を答えなさい。\n3x²＋4x－1',
    a: '2',
    b: '3',
    c: '4',
    d: '－1',
    explanation: '答え：2\n項ごとにわけて文字の数を数えましょう。\nx²があるので2ですね。',
  },
  {
    check: 'G2_taisho_M',
    question: '次の式は何次式ですか。\na²＋b²＋c²－6abc',
    a: '3次式',
    b: '2次式',
    c: '9次式',
    d: '6次式',
    explanation: '答え：3次式\n項ごとにわけて文字の数を数えましょう。\nabcがあるので3次式ですね。',
  },
  {
    check: 'G2_taisho_M',
    question: '百の位の数がa、十の位の数がb、一の位の数がcである3けたの整数を正しく表したものはどれ？',
    a: '100a＋10b＋c',
    b: 'a＋b＋c',
    c: 'abc',
    d: '他のどの選択肢も間違っている',
    explanation: '答え：100a+10b+c\n〇の位の数というのは、〇がいくつ分かを表します。\n百の位の数がaなら100がa個分、すなわち100aです。',
  },
  {
    check: 'G2_taisho_M',
    question: '次の式の各項の係数として、正しくないものはどれ？\nx³－2x²－x',
    a: '2',
    b: '－1',
    c: '1',
    d: '－2',
    explanation: '答え：2\nx³の係数は1、－2x²の係数は－2、－xの係数は－1ですね。\n－も含まれることに注意しましょう。',
  },
  {
    check: 'G2_taisho_M',
    question: '次の式について述べた文章のうち、正しくないものはどれ？\ 8x－8y＋8',
    a: 'xについて解くとx＝y－1となる',
    b: '1次式である',
    c: '8(x－y＋1) と等しい',
    d: 'x＝1，y＝－1のときの値は24である',
    explanation: '答え：xについて解くとx＝y－1となる\n〇〇について解けるのは「方程式」です。\nこの式には「＝」が含まれないため方程式ではありません。',
  },

  // 中２ 大正 理科
  {
    check: 'G2_taisho_SI',
    question: '体が多くの細胞で出来ている生物を何といいますか。',
    a: '多細胞生物',
    b: '単細胞生物',
    c: '組織',
    d: '個体',
    explanation: '単細胞生物は１つの細胞が生きるための全てのはたらきをします。',
  },
  {
    check: 'G2_taisho_SI',
    question: '動物の細胞にしか存在しないものとして適切ではないものは次のうちどれか。',
    a: '液胞',
    b: '細胞膜',
    c: '核',
    d: '細胞質',
    explanation: '植物細胞にしか存在しないものとして、液胞(細胞の活動によりできた物質が溶けた液で満たされたもの)・細胞壁(植物のからだを支えたり、守ったりするもの)・葉緑体(光合成をするもの)があります。',
  },
  {
    check: 'G2_taisho_SI',
    question: '根で吸収した水や水に溶けた養分が通る管を何というか。',
    a: '道管',
    b: '師管',
    c: '維管束',
    d: '葉脈',
    explanation: 'ウチの上水道管(茎で内側、葉で上側を通り水が通る道管)で覚えましょう。',
  },
  {
    check: 'G2_taisho_SI',
    question: '維管束が輪のように並ぶ植物は何でしょう。',
    a: '双子葉類',
    b: '単子葉類',
    c: 'シダ植物',
    d: 'コケ植物',
    explanation: '単子葉類は維管束がバラバラに存在します。',
  },
  {
    check: 'G2_taisho_SI',
    question: '光合成に必要なものとして適切ではないものはどれか。',
    a: 'デンプン',
    b: '二酸化炭素',
    c: '水',
    d: '光',
    explanation: '光合成は、二酸化炭素と水を材料とし、光エネルギーをつかって、葉緑体で酸素とデンプンを作り出します。',
  },
  {
    check: 'G2_taisho_SI',
    question: '消化液に含まれる、養分を分解するはたらきのある物質を何というか。',
    a: '消化酵素',
    b: '消化液',
    c: '消化管',
    d: '肺胞',
    explanation: '消化酵素の中には、だ液に含まれるアミラーゼ・胃液に含まれるペプシン、すい液に含まれるリパーゼなどがあります。',
  },
  {
    check: 'G2_taisho_SI',
    question: 'デンプンにはたらく消化液として適当でないものはどれか。',
    a: '胃液',
    b: 'だ液',
    c: 'すい液',
    d: '腸液',
    explanation: '',
  },
  {
    check: 'G2_taisho_SI',
    question: '次のうち消化酵素をもたない消化液はどれか。',
    a: '胆汁',
    b: '腸液',
    c: '胃液',
    d: 'だ液',
    explanation: '胆汁は消化酵素を持ちませんが、脂肪の分解を助けるはたらきをもちます。',
  },
  {
    check: 'G2_taisho_SI',
    question: 'デンプンは分解され、最終的になんという物質になるか。',
    a: 'ブドウ糖',
    b: 'アミノ酸',
    c: '脂肪酸',
    d: 'モノグリセリド',
    explanation: '',
  },
  {
    check: 'G2_taisho_SI',
    question: 'タンパク質は分解され、最終的になんという物質になるか。',
    a: 'アミノ酸',
    b: 'ブドウ糖',
    c: '脂肪酸',
    d: 'モノグリセリド',
    explanation: '',
  },
  {
    check: 'G2_taisho_SI',
    question: '脂肪は小腸に吸収されたあと、何という管に入るか。',
    a: 'リンパ管',
    b: '毛細血管',
    c: '道管',
    d: '師管',
    explanation: 'ブドウ糖とアミノ酸は毛細血管に入ります。',
  },
  {
    check: 'G2_taisho_SI',
    question: '息を吸うときの説明として正しいものはどれか。',
    a: 'ろっ骨が上がり、横隔膜が下がる',
    b: 'ろっ骨が上がり、横隔膜が上がる',
    c: 'ろっ骨が下がり、横隔膜が下がる',
    d: 'ろっ骨が下がり、横隔膜が上がる',
    explanation: '息を吸うときは胸腔を広くし、息を吐くときは胸腔を狭くするために、ろっ骨が下がり、横隔膜が上がります。',
  },
  {
    check: 'G2_taisho_SI',
    question: '血液の成分のうち、酸素の運搬をするものは次のうちどれか。',
    a: '赤血球',
    b: '白血球',
    c: '血小板',
    d: '血しょう',
    explanation: '赤血球は酸素の多いところでは酸素と結合し、酸素の少ないところでは酸素を手放す性質をもちます。',
  },
  {
    check: 'G2_taisho_SI',
    question: '血液の成分のうち、病原体を分解するものは次のうちどれか。',
    a: '白血球',
    b: '赤血球',
    c: '血小板',
    d: '血しょう',
    explanation: '白血球は病原体を食べて殺す性質をもちます。',
  },
  {
    check: 'G2_taisho_SI',
    question: '血液の成分のうち、血をかためるものは次のうちどれか。',
    a: '血小板',
    b: '赤血球',
    c: '白血球',
    d: '血しょう',
    explanation: '血小板は血をかためてかさぶたを作る性質をもちます。',
  },
  {
    check: 'G2_taisho_SI',
    question: '赤血球に含まれるヘモグロビンは何色の色素成分でしょう。',
    a: '赤色',
    b: '黄色',
    c: '無色透明',
    d: '緑色',
    explanation: '',
  },
  // 中２ 大正 社会

  //// 中２ 曙川南
  // 中２ 曙川南 英語
  {
    check: 'G2_akenan_E',
    question:'When I go to school,I take a bus.と同じ意味の英文はどれか',
    a:'I take a bus when I go to school.',
    b:'I take a bus,when I go to school.',
    c:'When I take a bus, I go to school.',
    d:'I go to school when I take a bus.',
    explanation:'When～,はコンマ無しで文末に置く事ができる',
  },
  {
    check: 'G2_akenan_E',
    question:'「私が家に帰ってきた時、父はテレビを見ていました」の意味の英文はどれか',
    a:'When I came home,my father was waching TV.',
    b:'When I came home,my father watched TV.',
    c:'When I was coming home,my father was watching TV.',
    d:'When I came home,my father is watching TV.',
    explanation:'時制の一致なのでwhenのカタマリも過去形にする',
  },
  {
    check: 'G2_akenan_E',    
    question:'「もし明日晴れたら、野球をするつもりです」の意味の英文はどれか',
    a:'If it is sunny tomorrow,I will play baseball.',
    b:'If it will be sunny tomorrow,I will play baseball.',
    c:'If it is sunny tomorrow,I play baseball.',
    d:'If it will be sunny tomorrow,I play baseball.',
    explanation:'tomorrowなど未来を表す単語があっても、Ifの中は現在形にする。',
  },
  {
    check: 'G2_akenan_E',    
    question:'I think（　　）the book is interesting.（　）に入る単語はどれか',
    a:'that',
    b:'and',
    c:'when',
    d:'if',
    explanation:'接続詞のthatは省略可能',
  },    

  // 中２ 曙川南 数学

  {
    check: 'G2_akenan_M',
    question: '次の式の次数を答えなさい。\n3x²＋4x－1',
    a: '2',
    b: '3',
    c: '4',
    d: '－1',
    explanation: '答え：2\n項ごとにわけて文字の数を数えましょう。\nx²があるので2ですね。',
  },
  {
    check: 'G2_akenan_M',
    question: '次の式は何次式ですか。\na²＋b²＋c²－6abc',
    a: '3次式',
    b: '2次式',
    c: '9次式',
    d: '6次式',
    explanation: '答え：3次式\n項ごとにわけて文字の数を数えましょう。\nabcがあるので3次式ですね。',
  },
  {
    check: 'G2_akenan_M',
    question: '百の位の数がa、十の位の数がb、一の位の数がcである3けたの整数を正しく表したものはどれ？',
    a: '100a＋10b＋c',
    b: 'a＋b＋c',
    c: 'abc',
    d: '他のどの選択肢も間違っている',
    explanation: '答え：100a+10b+c\n〇の位の数というのは、〇がいくつ分かを表します。\n百の位の数がaなら100がa個分、すなわち100aです。',
  },
  {
    check: 'G2_akenan_M',
    question: '次の式の各項の係数として、正しくないものはどれ？\nx³－2x²－x',
    a: '2',
    b: '－1',
    c: '1',
    d: '－2',
    explanation: '答え：2\nx³の係数は1、－2x²の係数は－2、－xの係数は－1ですね。\n－も含まれることに注意しましょう。',
  },
  {
    check: 'G2_akenan_M',
    question: '次の式について述べた文章のうち、正しくないものはどれ？\ 8x－8y＋8',
    a: 'xについて解くとx＝y－1となる',
    b: '1次式である',
    c: '8(x－y＋1) と等しい',
    d: 'x＝1，y＝－1のときの値は24である',
    explanation: '答え：xについて解くとx＝y－1となる\n〇〇について解けるのは「方程式」です。\nこの式には「＝」が含まれないため方程式ではありません。',
  },

  // 中２ 曙川南 理科
  {
    check: 'G2_akenan_SI',
    question: '体が多くの細胞で出来ている生物を何といいますか。',
    a: '多細胞生物',
    b: '単細胞生物',
    c: '組織',
    d: '個体',
    explanation: '単細胞生物は１つの細胞が生きるための全てのはたらきをします。',
  },
  {
    check: 'G2_akenan_SI',
    question: '動物の細胞にしか存在しないものとして適切ではないものは次のうちどれか。',
    a: '液胞',
    b: '細胞膜',
    c: '核',
    d: '細胞質',
    explanation: '植物細胞にしか存在しないものとして、液胞(細胞の活動によりできた物質が溶けた液で満たされたもの)・細胞壁(植物のからだを支えたり、守ったりするもの)・葉緑体(光合成をするもの)があります。',
  },
  {
    check: 'G2_akenan_SI',
    question: '根で吸収した水や水に溶けた養分が通る管を何というか。',
    a: '道管',
    b: '師管',
    c: '維管束',
    d: '葉脈',
    explanation: 'ウチの上水道管(茎で内側、葉で上側を通り水が通る道管)で覚えましょう。',
  },
  {
    check: 'G2_akenan_SI',
    question: '維管束が輪のように並ぶ植物は何でしょう。',
    a: '双子葉類',
    b: '単子葉類',
    c: 'シダ植物',
    d: 'コケ植物',
    explanation: '単子葉類は維管束がバラバラに存在します。',
  },
  {
    check: 'G2_akenan_SI',
    question: '光合成に必要なものとして適切ではないものはどれか。',
    a: 'デンプン',
    b: '二酸化炭素',
    c: '水',
    d: '光',
    explanation: '光合成は、二酸化炭素と水を材料とし、光エネルギーをつかって、葉緑体で酸素とデンプンを作り出します。',
  },
  {
    check: 'G2_akenan_SI',
    question: '消化液に含まれる、養分を分解するはたらきのある物質を何というか。',
    a: '消化酵素',
    b: '消化液',
    c: '消化管',
    d: '肺胞',
    explanation: '消化酵素の中には、だ液に含まれるアミラーゼ・胃液に含まれるペプシン、すい液に含まれるリパーゼなどがあります。',
  },
  {
    check: 'G2_akenan_SI',
    question: 'デンプンにはたらく消化液として適当でないものはどれか。',
    a: '胃液',
    b: 'だ液',
    c: 'すい液',
    d: '腸液',
    explanation: '',
  },
  {
    check: 'G2_akenan_SI',
    question: '次のうち消化酵素をもたない消化液はどれか。',
    a: '胆汁',
    b: '腸液',
    c: '胃液',
    d: 'だ液',
    explanation: '胆汁は消化酵素を持ちませんが、脂肪の分解を助けるはたらきをもちます。',
  },
  {
    check: 'G2_akenan_SI',
    question: 'デンプンは分解され、最終的になんという物質になるか。',
    a: 'ブドウ糖',
    b: 'アミノ酸',
    c: '脂肪酸',
    d: 'モノグリセリド',
    explanation: '',
  },
  {
    check: 'G2_akenan_SI',
    question: 'タンパク質は分解され、最終的になんという物質になるか。',
    a: 'アミノ酸',
    b: 'ブドウ糖',
    c: '脂肪酸',
    d: 'モノグリセリド',
    explanation: '',
  },
  {
    check: 'G2_akenan_SI',
    question: '脂肪は小腸に吸収されたあと、何という管に入るか。',
    a: 'リンパ管',
    b: '毛細血管',
    c: '道管',
    d: '師管',
    explanation: 'ブドウ糖とアミノ酸は毛細血管に入ります。',
  },
  {
    check: 'G2_akenan_SI',
    question: '息を吸うときの説明として正しいものはどれか。',
    a: 'ろっ骨が上がり、横隔膜が下がる',
    b: 'ろっ骨が上がり、横隔膜が上がる',
    c: 'ろっ骨が下がり、横隔膜が下がる',
    d: 'ろっ骨が下がり、横隔膜が上がる',
    explanation: '息を吸うときは胸腔を広くし、息を吐くときは胸腔を狭くするために、ろっ骨が下がり、横隔膜が上がります。',
  },
  {
    check: 'G2_akenan_SI',
    question: '血液の成分のうち、酸素の運搬をするものは次のうちどれか。',
    a: '赤血球',
    b: '白血球',
    c: '血小板',
    d: '血しょう',
    explanation: '赤血球は酸素の多いところでは酸素と結合し、酸素の少ないところでは酸素を手放す性質をもちます。',
  },
  {
    check: 'G2_akenan_SI',
    question: '血液の成分のうち、病原体を分解するものは次のうちどれか。',
    a: '白血球',
    b: '赤血球',
    c: '血小板',
    d: '血しょう',
    explanation: '白血球は病原体を食べて殺す性質をもちます。',
  },
  {
    check: 'G2_akenan_SI',
    question: '血液の成分のうち、血をかためるものは次のうちどれか。',
    a: '血小板',
    b: '赤血球',
    c: '白血球',
    d: '血しょう',
    explanation: '血小板は血をかためてかさぶたを作る性質をもちます。',
  },
  {
    check: 'G2_akenan_SI',
    question: '赤血球に含まれるヘモグロビンは何色の色素成分でしょう。',
    a: '赤色',
    b: '黄色',
    c: '無色透明',
    d: '緑色',
    explanation: '',
  },
  // 中２ 曙川南 社会

  //// 中２ 南高安
  // 中２ 南高安 英語
  {
    check: 'G2_nantaka_E',
    question:'When I go to school,I take a bus.と同じ意味の英文はどれか',
    a:'I take a bus when I go to school.',
    b:'I take a bus,when I go to school.',
    c:'When I take a bus, I go to school.',
    d:'I go to school when I take a bus.',
    explanation:'When～,はコンマ無しで文末に置く事ができる',
  },
  {
    check: 'G2_nantaka_E',
    question:'「私が家に帰ってきた時、父はテレビを見ていました」の意味の英文はどれか',
    a:'When I came home,my father was waching TV.',
    b:'When I came home,my father watched TV.',
    c:'When I was coming home,my father was watching TV.',
    d:'When I came home,my father is watching TV.',
    explanation:'時制の一致なのでwhenのカタマリも過去形にする',
  },
  {
    check: 'G2_nantaka_E',    
    question:'「もし明日晴れたら、野球をするつもりです」の意味の英文はどれか',
    a:'If it is sunny tomorrow,I will play baseball.',
    b:'If it will be sunny tomorrow,I will play baseball.',
    c:'If it is sunny tomorrow,I play baseball.',
    d:'If it will be sunny tomorrow,I play baseball.',
    explanation:'tomorrowなど未来を表す単語があっても、Ifの中は現在形にする。',
  },
  {
    check: 'G2_nantaka_E',    
    question:'I think（　　）the book is interesting.（　）に入る単語はどれか',
    a:'that',
    b:'and',
    c:'when',
    d:'if',
    explanation:'接続詞のthatは省略可能',
  },    

  // 中２ 南高安 数学
  {
    check: 'G2_nantaka_M',
    question: '次の式の次数を答えなさい。\n3x²＋4x－1',
    a: '2',
    b: '3',
    c: '4',
    d: '－1',
    explanation: '答え：2\n項ごとにわけて文字の数を数えましょう。\nx²があるので2ですね。',
  },
  {
    check: 'G2_nantaka_M',
    question: '次の式は何次式ですか。\na²＋b²＋c²－6abc',
    a: '3次式',
    b: '2次式',
    c: '9次式',
    d: '6次式',
    explanation: '答え：3次式\n項ごとにわけて文字の数を数えましょう。\nabcがあるので3次式ですね。',
  },
  {
    check: 'G2_nantaka_M',
    question: '百の位の数がa、十の位の数がb、一の位の数がcである3けたの整数を正しく表したものはどれ？',
    a: '100a＋10b＋c',
    b: 'a＋b＋c',
    c: 'abc',
    d: '他のどの選択肢も間違っている',
    explanation: '答え：100a+10b+c\n〇の位の数というのは、〇がいくつ分かを表します。\n百の位の数がaなら100がa個分、すなわち100aです。',
  },
  {
    check: 'G2_nantaka_M',
    question: '次の式の各項の係数として、正しくないものはどれ？\nx³－2x²－x',
    a: '2',
    b: '－1',
    c: '1',
    d: '－2',
    explanation: '答え：2\nx³の係数は1、－2x²の係数は－2、－xの係数は－1ですね。\n－も含まれることに注意しましょう。',
  },
  {
    check: 'G2_nantaka_M',
    question: '次の式について述べた文章のうち、正しくないものはどれ？\n 8x－8y＋8',
    a: 'xについて解くとx＝y－1となる',
    b: '1次式である',
    c: '8(x－y＋1) と等しい',
    d: 'x＝1，y＝－1のときの値は24である',
    explanation: '答え：xについて解くとx＝y－1となる\n〇〇について解けるのは「方程式」です。\nこの式には「＝」が含まれないため方程式ではありません。',
  },

  // 中２ 南高安 理科  
  {
    check: 'G2_nantaka_SI',
    question: '岩石が温度変化や水などの影響を受け、長い間に表面から崩れていくことを何というか。',
    a: '風化',
    b: '侵食',
    c: '運搬',
    d: '堆積',
    explanation: '流水が岩石などを削ることを「侵食」、削りとった岩石を運ぶことを「運搬」、削られた土砂が積もることを「堆積」といいます。',
  },
  {
    check: 'G2_nantaka_SI',
    question: '侵食によって川の上流にできる、深い谷のことを何というか。',
    a: 'Ｖ字谷',
    b: '扇状地',
    c: '三角州',
    d: 'フィヨルド',
    explanation: '',
  },
  {
    check: 'G2_nantaka_SI',
    question: 'れき・砂・泥のうち、河口の最も近くに堆積するものはどれか',
    a: 'れき',
    b: '砂',
    c: '泥',
    d: '決まりはない',
    explanation: '粒の大きいものほど河口近くに堆積します。',
  },
  {
    check: 'G2_nantaka_SI',
    question: '土砂や火山灰などの堆積物が、上に堆積したものの重みで押し固められてできた岩石を何というか。',
    a: '堆積岩',
    b: '火山岩',
    c: '火成岩',
    d: '深成岩',
    explanation: '',
  },
  {
    check: 'G2_nantaka_SI',
    question: '生物の死がいなどが堆積してできた岩石で、うすい塩酸をかけると二酸化炭素が発生するものを何というか。',
    a: '石灰岩',
    b: 'チャート',
    c: '凝灰岩',
    d: '砂岩',
    explanation: 'チャートも生物の死がいなどが堆積してできる岩石ですが、二酸化炭素が発生しません。',
  },
  {
    check: 'G2_nantaka_SI',
    question: '地層が地表に現れているところを何というか。',
    a: '露頭',
    b: '断層',
    c: '正断層',
    d: '逆断層',
    explanation: '',
  },
  {
    check: 'G2_nantaka_SI',
    question: '火山灰の層から、堆積当時、何があったことが分かるか。',
    a: '火山噴火が起こった',
    b: '恐竜がいた',
    c: '人間がいた',
    d: '生物がいなかった。',
    explanation: '',
  },
  {
    check: 'G2_nantaka_SI',
    question: 'サンヨウチュウが発見される地層に地質年代は何か。',
    a: '古生代',
    b: '中生代',
    c: '新生代',
    d: '現代',
    explanation: '',
  },
  {
    check: 'G2_nantaka_SI',
    question: '地層が波打ったように曲がったものを何というか。',
    a: 'しゅう曲',
    b: '隆起',
    c: '沈降',
    d: '断層',
    explanation: '',
  },
  {
    check: 'G2_nantaka_SI',
    question: 'ある物質から性質の異なる別の物質ができる変化を何というか。',
    a: '化学変化',
    b: '分解',
    c: '化合',
    d: '酸化',
    explanation: '化学反応ともいいます。',
  },
  {
    check: 'G2_nantaka_SI',
    question: '炭酸水素ナトリウムを加熱すると、炭酸水素ナトリウムが分解してできる気体は何か。',
    a: '二酸化炭素',
    b: '水',
    c: '炭酸ナトリウム',
    d: '酸素',
    explanation: '炭酸水素ナトリウムを熱分解すると二酸化炭素(気体)、水(液体)、炭酸ナトリウム(白い固体)ができます。',
  },
  {
    check: 'G2_nantaka_SI',
    question: '水を電気分解したとき、陽極側から発生する気体は何か。',
    a: '酸素',
    b: '水素',
    c: '窒素',
    d: '二酸化炭素',
    explanation: '水を電気分解すると、陽極側から酸素が、陰極側から水素が1：2で発生します。',
  },
  {
    check: 'G2_nantaka_SI',
    question: '物質をつくっているそれ以上分けることができない粒子を何というか。',
    a: '原子',
    b: '分子',
    c: '電子',
    d: '陽子',
    explanation: '',
  },
  {
    check: 'G2_nantaka_SI',
    question: '水素の元素記号はどれか。',
    a: 'Ｈ',
    b: 'Ｏ',
    c: 'Ｎ',
    d: 'Ｃ',
    explanation: 'Ｏは酸素、Ｎは窒素、Ｃは炭素です。',
  },
  {
    check: 'G2_nantaka_SI',
    question: 'Cuの物質名は何か。',
    a: '銅',
    b: '銀',
    c: 'マグネシウム',
    d: '鉄',
    explanation: '銀はAg、マグネシウムはMg、鉄はFeです。',
  },
  {
    check: 'G2_nantaka_SI',
    question: 'Ｈ₂Ｏの物質名は何か。',
    a: '水',
    b: '二酸化炭素',
    c: '食塩',
    d: '塩化銅',
    explanation: '二酸化炭素はCO₂、食塩はNaCl、塩化銅はCuCl₂です。',
  },
  {
    check: 'G2_nantaka_SI',
    question: 'アンモニアの化学式はどれか。',
    a: 'NH₃',
    b: 'HCl',
    c: 'CuO',
    d: 'Ag₂O',
    explanation: 'HClは塩化水素(塩酸)、CuOは酸化銅、Ag₂Oは酸化銀',
  },
  // 中２ 南高安 社会

  ////// 中３
  //// 中３ 亀井
  // 中３ 亀井 英語
  {
    check: 'G3_kamei_E',
    question:'現在完了進行形の形はどれか',
    a:'have/has been 動詞のing形',
    b:'have/has 動詞の過去分詞形',
    c:'had 動詞の過去分詞形',
    d:'have/has be 動詞のing形',
    explanation:'形はhave/has been動詞のingで「ずっと～し続けている」と訳す',
  },
  {
    check: 'G3_kamei_E',
    question:'受動態の形はどれか',
    a:'be動詞 動詞の過去分詞形',
    b:'一般動詞 動詞の過去分詞形',
    c:'be動詞　動詞の原形',
    d:'一般動詞 動詞の原形',
    explanation:'形はbe動詞 動詞の過去分詞形で「～される・～されている」と訳す',
  },
  {
    check: 'G3_kamei_E',
    question:'「私は去年から日本に住み続けている」の意味の英文はどれか',
    a:'I have lived in Japan since last year.',
    b:'I have been lived in Japan since last year.',
    c:'I have lived in Japan for last year.',
    d:'I have been lived in Japan for last year.',
    explanation:'liveやknowは状態動詞でingを付けれないので現在完了を使う',
  },
  {
    check: 'G3_kamei_E',
    question:'「どれくらい～」の意味はどれか',
    a:'How long～',
    b:'How many～',
    c:'How much～',
    d:'How old～',
    explanation:'',
  },
  {
    check: 'G3_kamei_E',
    question:'「私は３年間中国語を勉強し続けている」の意味の英文はどれか',
    a:'I have studied Chinese for three years.',
    b:'I have been studying Chinese for three years.',
    c:'I has studies Chinese for three years.',
    d:'I has been studying Chinese for three years.',
    explanation:'現在完了進行形にすると、飲まず食わずで３年間勉強し続けている事になり\n現実的に不可能なので現在完了を使う',
  },
  {
    check: 'G3_kamei_E',
    question:'「昨日からずっと雨が降り続いてます」の意味の英文はどれか',
    a:'It has been raining since yesterday.',
    b:'It had been raining since yesterday.',
    c:'It have been raining since yesterday.',
    d:'It has been raining for yesterday.',
    explanation:'yesterdayの過去を表す単語があるが、hasをhadにしない',
  },
  {
    check: 'G3_kamei_E',
    question:'They clean this room every day.を受動態の文にすると正しいのはどれか',
    a:'This room is cleaned every day.',
    b:'This room was cleaned every day.',
    c:'This room is clean every day.',
    d:'This room was clean every day.',
    explanation:'主語がTheyやWeならby以下は省略可能',
  },
  {
    check: 'G3_kamei_E',
    question:'English are spoken all over the world.を能動態の文に',
    a:'People speak English all over the world.',
    b:'People speaks English all over the world.',
    c:'People spoke English all over the world.',
    d:'People are speaking English all over the world.',
    explanation:'書かれていないので主語にはpeopleやtheyを使う',
  },
  // 中３ 亀井 数学
  {
    check: 'G3_kamei_M',
    question: '(x＋3)(x－7)＝？',
    a: 'x²－4x－21',
    b: 'x²＋4x＋21',
    c: 'x²－21x－4',
    d: 'x²＋10x＋21',
    explanation: '答え：x²－4x－21\n間違った人はしっかりと乗法公式を覚えなおしましょう！',
  },
  {
    check: 'G3_kamei_M',
    question: '(2x－1)²＝？',
    a: '4x²－4x＋1',
    b: '4x²＋4x－1',
    c: '4x²＋4x＋1',
    d: '4x²－4x－1',
    explanation: '答え：4x²－4x＋1\n間違った人はしっかりと乗法公式を覚えなおしましょう！',
  },
  {
    check: 'G3_kamei_M',
    question: '(4x－1)(4x＋1)＝？',
    a: '16x²－1',
    b: '16x²',
    c: '2x²－1',
    d: '16x²＋8x－1',
    explanation: '答え：4x²－4x＋1\n間違った人はしっかりと乗法公式を覚えなおしましょう！',
  },
  {
    check: 'G3_kamei_M',
    question: '9999²＝？',
    a: '99980001',
    b: '99999981',
    c: '99980981',
    d: '99988901',
    explanation: '答え：99980001\n9999＝10000－1なので、\n9999²＝(10000－1)²＝10000²－2×10000×1＋1\nこうすれば暗算でも解けますね。',
  },
  {
    check: 'G3_kamei_M',
    question: 'x²－10x－24＝？',
    a: '(x＋2)(x－12)',
    b: '(x＋4)(x－6)',
    c: '(x－4)(x－6)',
    d: '(x－2)(x＋12)',
    explanation: '答え：(x＋2)(x－12)\n間違った人はしっかりと因数分解の公式・乗法公式を覚えなおしましょう！',
  },
  {
    check: 'G3_kamei_M',
    question: '1001²－999²＝？',
    a: '4000',
    b: '9999',
    c: '2000',
    d: '19998',
    explanation: '答え：4000\n1001²－999²＝(1001＋999)(1001－999)＝2000×2\nこうすれば暗算でも解けますね。',
  },
  {
    check: 'G3_kamei_M',
    question: '連続する3つの奇数について、「最大の数の平方と最小の数の平方の差」を計算します。\n最小の数を(2x－1)とおいたとき、正しい式はどれ？',
    a: '(2x＋3)²－(2x－1)²',
    b: '(2x＋1)－(2x－1)',
    c: '{(2x＋3)－(2x－1)}²',
    d: '(2x＋1)(2x－1)',
    explanation: '答え：(2x＋3)²－(2x－1)²\n平方とは2乗のことです。\n最小の数が(2x－1)ですから、連続する3つの奇数は(2x－1)，(2x＋1)，(2x＋3)となりますね。',
  },

  // 中３ 亀井 理科
  {
    check: 'G3_kamei_SI',
    question: '１つの細胞が２つ以上に分かれることを何というか。',
    a: '細胞分裂',
    b: '分解',
    c: '化合',
    d: '昇華',
    explanation: '',
  },
  {
    check: 'G3_kamei_SI',
    question: '細胞分裂をする前とした直後で、細胞１個の大きさはどうなっているか。',
    a: '小さくなっている',
    b: '大きくなっている',
    c: '変わらない',
    d: '細胞によって異なる',
    explanation: '生物の成長は、①細胞の数を増やす。②それぞれの細胞が元の大きさになる。ことによって行われます。',
  },
  {
    check: 'G3_kamei_SI',
    question: '細胞分裂のとき、核の中に見られるひものようなものを何というか。',
    a: '染色体',
    b: 'DNA',
    c: '遺伝子',
    d: '受精卵',
    explanation: '',
  },
  {
    check: 'G3_kamei_SI',
    question: 'タマネギの根で細胞分裂を観察するとき、塩酸であたためるのはなぜか。',
    a: '細胞同士を離れやすくするため',
    b: '細胞の重なりをなくすため',
    c: '核を染色して見やすくするため',
    d: '脱色するため',
    explanation: 'カバーガラスを指の腹で押すのは、細胞同士の重なりをなくすため。酢酸カーミン液などを滴下するのは、核を染色するためです。',
  },
  {
    check: 'G3_kamei_SI',
    question: 'タマネギの根の先端付近に存在し、細胞分裂が盛んにおこなわれている部分を何というか。',
    a: '成長点',
    b: '分裂点',
    c: '成長部',
    d: '分裂部',
    explanation: '',
  },
  {
    check: 'G3_kamei_SI',
    question: '雄と雌がかかわらない生殖のことを何というか。',
    a: '無性生殖',
    b: '有性生殖',
    c: '顕性生殖',
    d: '潜性生殖',
    explanation: '反対に、雄と雌がかかわる生殖を有性生殖といいます。',
  },
  {
    check: 'G3_kamei_SI',
    question: '雄と雌の生殖細胞の核が結びつくことを何というか。',
    a: '受精',
    b: '受粉',
    c: '化合',
    d: '合体',
    explanation: '',
  },
  {
    check: 'G3_kamei_SI',
    question: '生殖細胞をつくるときの、特別な細胞分裂を何というか。',
    a: '減数分裂',
    b: '体細胞分裂',
    c: '生殖分裂',
    d: '特別分裂',
    explanation: '',
  },
  {
    check: 'G3_kamei_SI',
    question: '減数分裂の前後で、染色体の数はどうなっているか。',
    a: '1/2になる',
    b: '1/3になる',
    c: '変わらない',
    d: '2倍になる',
    explanation: '',
  },
  {
    check: 'G3_kamei_SI',
    question: '受精卵は細胞分裂を繰り返しやがて何になるか。',
    a: '胚',
    b: '生物',
    c: '植物',
    d: '子ども',
    explanation: '動物も植物も、受精卵は細胞分裂を繰り返し、やがて胚になります',
  },
  {
    check: 'G3_kamei_SI',
    question: '動物の有性生殖において、受精卵から成体になるまでの過程を何というか。',
    a: '発生',
    b: '成長',
    c: '出産',
    d: '孵化',
    explanation: '',
  },
  {
    check: 'G3_kamei_SI',
    question: '生物のもつ形や性質などの特徴を何というか。',
    a: '形質',
    b: '外見',
    c: '見た目',
    d: '様子',
    explanation: '',
  },
  {
    check: 'G3_kamei_SI',
    question: '子が親の染色体をそのまま受け継ぐものとして正しいのは次のうちどれか。',
    a: '無性生殖',
    b: '有性生殖',
    c: '無性生殖と有性生殖',
    d: '無性生殖でも有性生殖でもない',
    explanation: '有性生殖では、子は両親から半分ずつ染色体を受け継ぎます。',
  },
  {
    check: 'G3_kamei_SI',
    question: '対立形質をもつ純系どうしをかけ合わせたとき、子に現れる方の形質を何というか。',
    a: '顕性形質',
    b: '潜性形質',
    c: '有性形質',
    d: '無性形質',
    explanation: '子に現れない方の形質を潜性形質といいます。',
  },
  {
    check: 'G3_kamei_SI',
    question: '遺伝子の本体をアルファベット3文字で表すと何か。',
    a: 'ＤＮＡ',
    b: 'ＤＨＡ',
    c: 'ＢＴＢ',
    d: 'ＰＥＴ',
    explanation: '',
  },
  {
    check: 'G3_kamei_SI',
    question: '丸い種子をつくる純系のエンドウと、しわのある種子をつくる純系のエンドウをかけ合わせてできた子を自家受粉して孫の代を得たとき、丸い種子としわのある種子の比はどうなるか。　',
    a: '3：1',
    b: '2：1',
    c: '1：1',
    d: '4：1',
    explanation: '',
  },
  {
    check: 'G3_kamei_SI',
    question: '磁力がはたらく空間を何というか。',
    a: '磁界',
    b: '磁力線',
    c: 'コイル',
    d: '方位磁針',
    explanation: '磁界の向きにそって滑らかに引いた線を磁力線といいます。',
  },
  {
    check: 'G3_kamei_SI',
    question: '磁界の強さを強くする方法として適切でないものはどれか。',
    a: '電流の向きを変える',
    b: 'コイルの巻き数を増やす',
    c: '電流の大きさを大きくする',
    d: 'コイルに鉄心を入れる',
    explanation: '',
  },
  {
    check: 'G3_kamei_SI',
    question: '磁界の中を流れる電流は、磁界の向きと電流の向きの両方に対して、どのような向きに力を受けるか。',
    a: '垂直',
    b: '平行',
    c: '同じ',
    d: '反対',
    explanation: 'フレミングの左手の法則を使って考えましょう。',
  },
  {
    check: 'G3_kamei_SI',
    question: 'コイルの中の磁界が変化すると、コイルに電流を流そうとする電圧が生じる現象を何というか。',
    a: '電磁誘導',
    b: '右ねじの法則',
    c: '磁力',
    d: '誘導電流',
    explanation: '電磁誘導によって流れる電流を誘導電流といいます。',
  },
  // 中３ 亀井 社会
  {
    check: 'G3_kamei_SS',
    question: 'バルカン半島はたくさんの軍隊が派遣されたため、「ヨーロッパの〇〇〇」と呼ばれました。〇に入る３文字は？',
    a: '火薬庫',
    b: '新世界',
    c: '中心地',
    d: '非常識',
    explanation: '答え：バルカン半島＝「ヨーロッパの火薬庫」テストに出そうですね～',
  },    
  {
    check: 'G3_kamei_SS',
    question: '日本が第一次世界大戦に参戦した理由は次のうちどれ？',
    a: '日英同盟があったから',
    b: '日清戦争に勝ち、勝算があったから',
    c: '資源を獲得したかったから',
    d: 'ノリで',
    explanation: '答え：その場のノリではありません（笑）1902年に締結した日英同盟で、どちらかの国が戦争に入った場合は支援することが約束されていました。',
  },    
  {
    check: 'G3_kamei_SS',    
    question: '第一次世界大戦が終わることになったきっかけは？',
    a: 'ロシア革命',
    b: '米騒動',
    c: 'ワシントン会議',
    d: '勢いで',
    explanation: '答え：その場の勢いではありません（笑）1917年にロシアで社会主義化しようとする国民の動きがあり、それが自分の国にも飛び火してくるのを恐れて、各国が軍隊をシベリアに派遣しました。そのことを日本では「シベリア出兵」と言いますね！',
  },    
  {
    check: 'G3_kamei_SS',    
    question: 'ロシア革命を指導したリーダーは？',
    a: 'レーニン',
    b: 'ゴルバチョフ',
    c: 'プーチン',
    d: 'プーさん',
    explanation: '答え：レーニンですね！今回の範囲で、もう一人、ロシアの指導者「スターリン」が出てきますが、これは世界恐慌のときに「五か年計画」を指導した人ですね！ハチミツ大好きプーさんではありません！',
  },    
  {
    check: 'G3_kamei_SS',    
    question: '第一次世界大戦は、それまでの戦争と何が大きく違っていたでしょうか？間違っているものを1つ選んでね！',
    a: '多くの民間人が殺された',
    b: '多くの新兵器（戦車や飛行機、毒ガスなど）が投入された',
    c: '多くの国が参戦した',
    d: '総力戦（戦争の長期化）になった',
    explanation: '答え：民間人がたくさん殺されたのは、戦争の歴史ではほとんどです。「世界大戦」と言われる理由は、多くの国が参戦することになったからですね！',
  },    
  {
    check: 'G3_kamei_SS',    
    question: '1930年、浜口雄幸内閣総理大臣が狙撃されたのは、何という条約を結んだことに一部の国民が不満をもったからでしょうか？',
    a: 'ロンドン海軍軍縮条約',
    b: 'ポーツマス条約',
    c: 'ベルサイユ条約',
    d: 'ワシントン海軍軍縮条約',
    explanation: '答え：ロンドン海軍軍縮条約では、補助艦の保有量を、米10英10日7と定めたことに対して、「弱腰外交」と批判されました。ワシントン海軍軍縮条約は1921年で、主力艦の保有量を米5英5日3と定められました！',
  },    
  {
    check: 'G3_kamei_SS',    
    question: '1919年、敗戦国のドイツでは、ある憲法が制定されたことで、普通選挙法が実現しました。その憲法は？',
    a: 'ワイマール憲法',
    b: '日本国憲法',
    c: 'オカマ憲法',
    d: 'ネイマール憲法',
    explanation: '答え：ワイマール憲法は、世界初！「社会権」を定めたことでも有名です！',
  },    
  {
    check: 'G3_kamei_SS',    
    question: '民本主義という、現在の民主主義の考えを主張した政治家は？',
    a: '吉野作造',
    b: '美濃部達吉',
    c: '芥川龍之介',
    d: 'ネイマール',
    explanation: '答え：美濃部達吉は「天皇機関説」を主張した憲法家です！芥川龍之介は「鼻」「羅生門」などの小説を発行した人ですね！',
  },    
  {
    check: 'G3_kamei_SS',    
    question: '1925年に制定された普通選挙法により、選挙権はどのような条件になりましたか？',
    a: '25歳以上の男子',
    b: '直接国税3円以上納める25歳以上の男子',
    c: '20歳以上の男女',
    d: '18歳以上の男女',
    explanation: '答え：直接国税の条件がなくなったことを「普通」選挙と言います！現在の選挙権は18歳以上の男女ですね！',
  },    
  {
    check: 'G3_kamei_SS',    
    question: '1929年に起こった世界恐慌に対して、アメリカがとった政策は次のうちどれ？',
    a: '公共事業を増やすなどのニューディール政策',
    b: '植民地以外からの輸出品には高い関税をかけるブロック経済政策',
    c: '反民主主義を掲げ、独裁者による熱狂的なファシズム',
    d: '他国に侵略し、金や資源などを奪う帝国主義',
    explanation: '答え：アメリカは、ニューディール政策をとり、失業者を雇用するために、テネシー川の修復やダム建設などを行いました！',
  },    
    
  //// 中３ 龍華
  // 中３ 龍華 英語
  {
    check: 'G3_ryuge_E',
    question:'現在完了進行形の形はどれか',
    a:'have/has been 動詞のing形',
    b:'have/has 動詞の過去分詞形',
    c:'had 動詞の過去分詞形',
    d:'have/has be 動詞のing形',
    explanation:'形はhave/has been動詞のingで「ずっと～し続けている」と訳す',
  },
  {
    check: 'G3_ryuge_E',
    question:'受動態の形はどれか',
    a:'be動詞 動詞の過去分詞形',
    b:'一般動詞 動詞の過去分詞形',
    c:'be動詞　動詞の原形',
    d:'一般動詞 動詞の原形',
    explanation:'形はbe動詞 動詞の過去分詞形で「～される・～されている」と訳す',
  },
  {
    check: 'G3_ryuge_E',
    question:'「私は去年から日本に住み続けている」の意味の英文はどれか',
    a:'I have lived in Japan since last year.',
    b:'I have been lived in Japan since last year.',
    c:'I have lived in Japan for last year.',
    d:'I have been lived in Japan for last year.',
    explanation:'liveやknowは状態動詞でingを付けれないので現在完了を使う',
  },
  {
    check: 'G3_ryuge_E',
    question:'「どれくらい～」の意味はどれか',
    a:'How long～',
    b:'How many～',
    c:'How much～',
    d:'How old～',
    explanation:'',
  },
  {
    check: 'G3_ryuge_E',
    question:'「私は３年間中国語を勉強し続けている」の意味の英文はどれか',
    a:'I have studied Chinese for three years.',
    b:'I have been studying Chinese for three years.',
    c:'I has studies Chinese for three years.',
    d:'I has been studying Chinese for three years.',
    explanation:'現在完了進行形にすると、飲まず食わずで３年間勉強し続けている事になり\n現実的に不可能なので現在完了を使う',
  },
  {
    check: 'G3_ryuge_E',
    question:'「昨日からずっと雨が降り続いてます」の意味の英文はどれか',
    a:'It has been raining since yesterday.',
    b:'It had been raining since yesterday.',
    c:'It have been raining since yesterday.',
    d:'It has been raining for yesterday.',
    explanation:'yesterdayの過去を表す単語があるが、hasをhadにしない',
  },
  {
    check: 'G3_ryuge_E',
    question:'They clean this room every day.を受動態の文にすると正しいのはどれか',
    a:'This room is cleaned every day.',
    b:'This room was cleaned every day.',
    c:'This room is clean every day.',
    d:'This room was clean every day.',
    explanation:'主語がTheyやWeならby以下は省略可能',
  },
  {
    check: 'G3_ryuge_E',
    question:'English are spoken all over the world.を能動態の文に',
    a:'People speak English all over the world.',
    b:'People speaks English all over the world.',
    c:'People spoke English all over the world.',
    d:'People are speaking English all over the world.',
    explanation:'書かれていないので主語にはpeopleやtheyを使う',
  },
  // 中３ 龍華 数学
  {
    check: 'G3_ryuge_M',
    question: '(x＋3)(x－7)＝？',
    a: 'x²－4x－21',
    b: 'x²＋4x＋21',
    c: 'x²－21x－4',
    d: 'x²＋10x＋21',
    explanation: '答え：x²－4x－21\n間違った人はしっかりと乗法公式を覚えなおしましょう！',
  },
  {
    check: 'G3_ryuge_M',
    question: '(2x－1)²＝？',
    a: '4x²－4x＋1',
    b: '4x²＋4x－1',
    c: '4x²＋4x＋1',
    d: '4x²－4x－1',
    explanation: '答え：4x²－4x＋1\n間違った人はしっかりと乗法公式を覚えなおしましょう！',
  },
  {
    check: 'G3_ryuge_M',
    question: '(4x－1)(4x＋1)＝？',
    a: '16x²－1',
    b: '16x²',
    c: '2x²－1',
    d: '16x²＋8x－1',
    explanation: '答え：4x²－4x＋1\n間違った人はしっかりと乗法公式を覚えなおしましょう！',
  },
  {
    check: 'G3_ryuge_M',
    question: '9999²＝？',
    a: '99980001',
    b: '99999981',
    c: '99980981',
    d: '99988901',
    explanation: '答え：99980001\n9999＝10000－1なので、\n9999²＝(10000－1)²＝10000²－2×10000×1＋1\nこうすれば暗算でも解けますね。',
  },
  {
    check: 'G3_ryuge_M',
    question: 'x²－10x－24＝？',
    a: '(x＋2)(x－12)',
    b: '(x＋4)(x－6)',
    c: '(x－4)(x－6)',
    d: '(x－2)(x＋12)',
    explanation: '答え：(x＋2)(x－12)\n間違った人はしっかりと因数分解の公式・乗法公式を覚えなおしましょう！',
  },
  {
    check: 'G3_ryuge_M',
    question: '1001²－999²＝？',
    a: '4000',
    b: '9999',
    c: '2000',
    d: '19998',
    explanation: '答え：4000\n1001²－999²＝(1001＋999)(1001－999)＝2000×2\nこうすれば暗算でも解けますね。',
  },
  {
    check: 'G3_ryuge_M',
    question: '連続する3つの奇数について、「最大の数の平方と最小の数の平方の差」を計算します。\n最小の数を(2x－1)とおいたとき、正しい式はどれ？',
    a: '(2x＋3)²－(2x－1)²',
    b: '(2x＋1)－(2x－1)',
    c: '{(2x＋3)－(2x－1)}²',
    d: '(2x＋1)(2x－1)',
    explanation: '答え：(2x＋3)²－(2x－1)²\n平方とは2乗のことです。\n最小の数が(2x－1)ですから、連続する3つの奇数は(2x－1)，(2x＋1)，(2x＋3)となりますね。',
  },

  // 中３ 龍華 理科
  {
    check: 'G3_ryuge_SI',
    question: '１つの細胞が２つ以上に分かれることを何というか。',
    a: '細胞分裂',
    b: '分解',
    c: '化合',
    d: '昇華',
    explanation: '',
  },
  {
    check: 'G3_ryuge_SI',
    question: '細胞分裂をする前とした直後で、細胞１個の大きさはどうなっているか。',
    a: '小さくなっている',
    b: '大きくなっている',
    c: '変わらない',
    d: '細胞によって異なる',
    explanation: '生物の成長は、①細胞の数を増やす。②それぞれの細胞が元の大きさになる。ことによって行われます。',
  },
  {
    check: 'G3_ryuge_SI',
    question: '細胞分裂のとき、核の中に見られるひものようなものを何というか。',
    a: '染色体',
    b: 'DNA',
    c: '遺伝子',
    d: '受精卵',
    explanation: '',
  },
  {
    check: 'G3_ryuge_SI',
    question: 'タマネギの根で細胞分裂を観察するとき、塩酸であたためるのはなぜか。',
    a: '細胞同士を離れやすくするため',
    b: '細胞の重なりをなくすため',
    c: '核を染色して見やすくするため',
    d: '脱色するため',
    explanation: 'カバーガラスを指の腹で押すのは、細胞同士の重なりをなくすため。酢酸カーミン液などを滴下するのは、核を染色するためです。',
  },
  {
    check: 'G3_ryuge_SI',
    question: 'タマネギの根の先端付近に存在し、細胞分裂が盛んにおこなわれている部分を何というか。',
    a: '成長点',
    b: '分裂点',
    c: '成長部',
    d: '分裂部',
    explanation: '',
  },
  {
    check: 'G3_ryuge_SI',
    question: '雄と雌がかかわらない生殖のことを何というか。',
    a: '無性生殖',
    b: '有性生殖',
    c: '顕性生殖',
    d: '潜性生殖',
    explanation: '反対に、雄と雌がかかわる生殖を有性生殖といいます。',
  },
  {
    check: 'G3_ryuge_SI',
    question: '雄と雌の生殖細胞の核が結びつくことを何というか。',
    a: '受精',
    b: '受粉',
    c: '化合',
    d: '合体',
    explanation: '',
  },
  {
    check: 'G3_ryuge_SI',
    question: '生殖細胞をつくるときの、特別な細胞分裂を何というか。',
    a: '減数分裂',
    b: '体細胞分裂',
    c: '生殖分裂',
    d: '特別分裂',
    explanation: '',
  },
  {
    check: 'G3_ryuge_SI',
    question: '減数分裂の前後で、染色体の数はどうなっているか。',
    a: '1/2になる',
    b: '1/3になる',
    c: '変わらない',
    d: '2倍になる',
    explanation: '',
  },
  {
    check: 'G3_ryuge_SI',
    question: '受精卵は細胞分裂を繰り返しやがて何になるか。',
    a: '胚',
    b: '生物',
    c: '植物',
    d: '子ども',
    explanation: '動物も植物も、受精卵は細胞分裂を繰り返し、やがて胚になります',
  },
  {
    check: 'G3_ryuge_SI',
    question: '動物の有性生殖において、受精卵から成体になるまでの過程を何というか。',
    a: '発生',
    b: '成長',
    c: '出産',
    d: '孵化',
    explanation: '',
  },
  {
    check: 'G3_ryuge_SI',
    question: '生物のもつ形や性質などの特徴を何というか。',
    a: '形質',
    b: '外見',
    c: '見た目',
    d: '様子',
    explanation: '',
  },
  {
    check: 'G3_ryuge_SI',
    question: '子が親の染色体をそのまま受け継ぐものとして正しいのは次のうちどれか。',
    a: '無性生殖',
    b: '有性生殖',
    c: '無性生殖と有性生殖',
    d: '無性生殖でも有性生殖でもない',
    explanation: '有性生殖では、子は両親から半分ずつ染色体を受け継ぎます。',
  },
  {
    check: 'G3_ryuge_SI',
    question: '対立形質をもつ純系どうしをかけ合わせたとき、子に現れる方の形質を何というか。',
    a: '顕性形質',
    b: '潜性形質',
    c: '有性形質',
    d: '無性形質',
    explanation: '子に現れない方の形質を潜性形質といいます。',
  },
  {
    check: 'G3_ryuge_SI',
    question: '遺伝子の本体をアルファベット3文字で表すと何か。',
    a: 'ＤＮＡ',
    b: 'ＤＨＡ',
    c: 'ＢＴＢ',
    d: 'ＰＥＴ',
    explanation: '',
  },
  {
    check: 'G3_ryuge_SI',
    question: '丸い種子をつくる純系のエンドウと、しわのある種子をつくる純系のエンドウをかけ合わせてできた子を自家受粉して孫の代を得たとき、丸い種子としわのある種子の比はどうなるか。　',
    a: '3：1',
    b: '2：1',
    c: '1：1',
    d: '4：1',
    explanation: '',
  },
  // 中３ 龍華 社会

  //// 中３ 大正
  // 中３ 大正 英語
  {
    check: 'G3_taisho_E',
    question:'現在完了進行形の形はどれか',
    a:'have/has been 動詞のing形',
    b:'have/has 動詞の過去分詞形',
    c:'had 動詞の過去分詞形',
    d:'have/has be 動詞のing形',
    explanation:'形はhave/has been動詞のingで「ずっと～し続けている」と訳す',
  },
  {
    check: 'G3_taisho_E',
    question:'受動態の形はどれか',
    a:'be動詞 動詞の過去分詞形',
    b:'一般動詞 動詞の過去分詞形',
    c:'be動詞　動詞の原形',
    d:'一般動詞 動詞の原形',
    explanation:'形はbe動詞 動詞の過去分詞形で「～される・～されている」と訳す',
  },
  {
    check: 'G3_taisho_E',
    question:'「私は去年から日本に住み続けている」の意味の英文はどれか',
    a:'I have lived in Japan since last year.',
    b:'I have been lived in Japan since last year.',
    c:'I have lived in Japan for last year.',
    d:'I have been lived in Japan for last year.',
    explanation:'liveやknowは状態動詞でingを付けれないので現在完了を使う',
  },
  {
    check: 'G3_taisho_E',
    question:'「どれくらい～」の意味はどれか',
    a:'How long～',
    b:'How many～',
    c:'How much～',
    d:'How old～',
    explanation:'',
  },
  {
    check: 'G3_taisho_E',
    question:'「私は３年間中国語を勉強し続けている」の意味の英文はどれか',
    a:'I have studied Chinese for three years.',
    b:'I have been studying Chinese for three years.',
    c:'I has studies Chinese for three years.',
    d:'I has been studying Chinese for three years.',
    explanation:'現在完了進行形にすると、飲まず食わずで３年間勉強し続けている事になり\n現実的に不可能なので現在完了を使う',
  },
  {
    check: 'G3_taisho_E',
    question:'「昨日からずっと雨が降り続いてます」の意味の英文はどれか',
    a:'It has been raining since yesterday.',
    b:'It had been raining since yesterday.',
    c:'It have been raining since yesterday.',
    d:'It has been raining for yesterday.',
    explanation:'yesterdayの過去を表す単語があるが、hasをhadにしない',
  },
  {
    check: 'G3_taisho_E',
    question:'They clean this room every day.を受動態の文にすると正しいのはどれか',
    a:'This room is cleaned every day.',
    b:'This room was cleaned every day.',
    c:'This room is clean every day.',
    d:'This room was clean every day.',
    explanation:'主語がTheyやWeならby以下は省略可能',
  },
  {
    check: 'G3_taisho_E',
    question:'English are spoken all over the world.を能動態の文に',
    a:'People speak English all over the world.',
    b:'People speaks English all over the world.',
    c:'People spoke English all over the world.',
    d:'People are speaking English all over the world.',
    explanation:'書かれていないので主語にはpeopleやtheyを使う',
  },
  // 中３ 大正 数学
  {
    check: 'G3_taisho_M',
    question: '(x＋3)(x－7)＝？',
    a: 'x²－4x－21',
    b: 'x²＋4x＋21',
    c: 'x²－21x－4',
    d: 'x²＋10x＋21',
    explanation: '答え：x²－4x－21\n間違った人はしっかりと乗法公式を覚えなおしましょう！',
  },
  {
    check: 'G3_taisho_M',
    question: '(2x－1)²＝？',
    a: '4x²－4x＋1',
    b: '4x²＋4x－1',
    c: '4x²＋4x＋1',
    d: '4x²－4x－1',
    explanation: '答え：4x²－4x＋1\n間違った人はしっかりと乗法公式を覚えなおしましょう！',
  },
  {
    check: 'G3_taisho_M',
    question: '(4x－1)(4x＋1)＝？',
    a: '16x²－1',
    b: '16x²',
    c: '2x²－1',
    d: '16x²＋8x－1',
    explanation: '答え：4x²－4x＋1\n間違った人はしっかりと乗法公式を覚えなおしましょう！',
  },
  {
    check: 'G3_taisho_M',
    question: '9999²＝？',
    a: '99980001',
    b: '99999981',
    c: '99980981',
    d: '99988901',
    explanation: '答え：99980001\n9999＝10000－1なので、\n9999²＝(10000－1)²＝10000²－2×10000×1＋1\nこうすれば暗算でも解けますね。',
  },
  {
    check: 'G3_taisho_M',
    question: 'x²－10x－24＝？',
    a: '(x＋2)(x－12)',
    b: '(x＋4)(x－6)',
    c: '(x－4)(x－6)',
    d: '(x－2)(x＋12)',
    explanation: '答え：(x＋2)(x－12)\n間違った人はしっかりと因数分解の公式・乗法公式を覚えなおしましょう！',
  },
  {
    check: 'G3_taisho_M',
    question: '1001²－999²＝？',
    a: '4000',
    b: '9999',
    c: '2000',
    d: '19998',
    explanation: '答え：4000\n1001²－999²＝(1001＋999)(1001－999)＝2000×2\nこうすれば暗算でも解けますね。',
  },
  {
    check: 'G3_taisho_M',
    question: '連続する3つの奇数について、「最大の数の平方と最小の数の平方の差」を計算します。\n最小の数を(2x－1)とおいたとき、正しい式はどれ？',
    a: '(2x＋3)²－(2x－1)²',
    b: '(2x＋1)－(2x－1)',
    c: '{(2x＋3)－(2x－1)}²',
    d: '(2x＋1)(2x－1)',
    explanation: '答え：(2x＋3)²－(2x－1)²\n平方とは2乗のことです。\n最小の数が(2x－1)ですから、連続する3つの奇数は(2x－1)，(2x＋1)，(2x＋3)となりますね。',
  },

  // 中３ 大正 理科
  {
    check: 'G3_taisho_SI',
    question: '１つの細胞が２つ以上に分かれることを何というか。',
    a: '細胞分裂',
    b: '分解',
    c: '化合',
    d: '昇華',
    explanation: '',
  },
  {
    check: 'G3_taisho_SI',
    question: '細胞分裂をする前とした直後で、細胞１個の大きさはどうなっているか。',
    a: '小さくなっている',
    b: '大きくなっている',
    c: '変わらない',
    d: '細胞によって異なる',
    explanation: '生物の成長は、①細胞の数を増やす。②それぞれの細胞が元の大きさになる。ことによって行われます。',
  },
  {
    check: 'G3_taisho_SI',
    question: '細胞分裂のとき、核の中に見られるひものようなものを何というか。',
    a: '染色体',
    b: 'DNA',
    c: '遺伝子',
    d: '受精卵',
    explanation: '',
  },
  {
    check: 'G3_taisho_SI',
    question: 'タマネギの根で細胞分裂を観察するとき、塩酸であたためるのはなぜか。',
    a: '細胞同士を離れやすくするため',
    b: '細胞の重なりをなくすため',
    c: '核を染色して見やすくするため',
    d: '脱色するため',
    explanation: 'カバーガラスを指の腹で押すのは、細胞同士の重なりをなくすため。酢酸カーミン液などを滴下するのは、核を染色するためです。',
  },
  {
    check: 'G3_taisho_SI',
    question: 'タマネギの根の先端付近に存在し、細胞分裂が盛んにおこなわれている部分を何というか。',
    a: '成長点',
    b: '分裂点',
    c: '成長部',
    d: '分裂部',
    explanation: '',
  },
  {
    check: 'G3_taisho_SI',
    question: '雄と雌がかかわらない生殖のことを何というか。',
    a: '無性生殖',
    b: '有性生殖',
    c: '顕性生殖',
    d: '潜性生殖',
    explanation: '反対に、雄と雌がかかわる生殖を有性生殖といいます。',
  },
  {
    check: 'G3_taisho_SI',
    question: '雄と雌の生殖細胞の核が結びつくことを何というか。',
    a: '受精',
    b: '受粉',
    c: '化合',
    d: '合体',
    explanation: '',
  },
  {
    check: 'G3_taisho_SI',
    question: '生殖細胞をつくるときの、特別な細胞分裂を何というか。',
    a: '減数分裂',
    b: '体細胞分裂',
    c: '生殖分裂',
    d: '特別分裂',
    explanation: '',
  },
  {
    check: 'G3_taisho_SI',
    question: '減数分裂の前後で、染色体の数はどうなっているか。',
    a: '1/2になる',
    b: '1/3になる',
    c: '変わらない',
    d: '2倍になる',
    explanation: '',
  },
  {
    check: 'G3_taisho_SI',
    question: '受精卵は細胞分裂を繰り返しやがて何になるか。',
    a: '胚',
    b: '生物',
    c: '植物',
    d: '子ども',
    explanation: '動物も植物も、受精卵は細胞分裂を繰り返し、やがて胚になります',
  },
  {
    check: 'G3_taisho_SI',
    question: '動物の有性生殖において、受精卵から成体になるまでの過程を何というか。',
    a: '発生',
    b: '成長',
    c: '出産',
    d: '孵化',
    explanation: '',
  },
  {
    check: 'G3_taisho_SI',
    question: '生物のもつ形や性質などの特徴を何というか。',
    a: '形質',
    b: '外見',
    c: '見た目',
    d: '様子',
    explanation: '',
  },
  {
    check: 'G3_taisho_SI',
    question: '子が親の染色体をそのまま受け継ぐものとして正しいのは次のうちどれか。',
    a: '無性生殖',
    b: '有性生殖',
    c: '無性生殖と有性生殖',
    d: '無性生殖でも有性生殖でもない',
    explanation: '有性生殖では、子は両親から半分ずつ染色体を受け継ぎます。',
  },
  {
    check: 'G3_taisho_SI',
    question: '対立形質をもつ純系どうしをかけ合わせたとき、子に現れる方の形質を何というか。',
    a: '顕性形質',
    b: '潜性形質',
    c: '有性形質',
    d: '無性形質',
    explanation: '子に現れない方の形質を潜性形質といいます。',
  },
  {
    check: 'G3_taisho_SI',
    question: '遺伝子の本体をアルファベット3文字で表すと何か。',
    a: 'ＤＮＡ',
    b: 'ＤＨＡ',
    c: 'ＢＴＢ',
    d: 'ＰＥＴ',
    explanation: '',
  },
  {
    check: 'G3_taisho_SI',
    question: '丸い種子をつくる純系のエンドウと、しわのある種子をつくる純系のエンドウをかけ合わせてできた子を自家受粉して孫の代を得たとき、丸い種子としわのある種子の比はどうなるか。　',
    a: '3：1',
    b: '2：1',
    c: '1：1',
    d: '4：1',
    explanation: '',
  },

  // 中３ 大正 社会

  //// 中３ 曙川南
  // 中３ 曙川南 英語
  {
    check: 'G3_akenan_E',
    question:'現在完了進行形の形はどれか',
    a:'have/has been 動詞のing形',
    b:'have/has 動詞の過去分詞形',
    c:'had 動詞の過去分詞形',
    d:'have/has be 動詞のing形',
    explanation:'形はhave/has been動詞のingで「ずっと～し続けている」と訳す',
  },
  {
    check: 'G3_akenan_E',
    question:'受動態の形はどれか',
    a:'be動詞 動詞の過去分詞形',
    b:'一般動詞 動詞の過去分詞形',
    c:'be動詞　動詞の原形',
    d:'一般動詞 動詞の原形',
    explanation:'形はbe動詞 動詞の過去分詞形で「～される・～されている」と訳す',
  },
  {
    check: 'G3_akenan_E',
    question:'「私は去年から日本に住み続けている」の意味の英文はどれか',
    a:'I have lived in Japan since last year.',
    b:'I have been lived in Japan since last year.',
    c:'I have lived in Japan for last year.',
    d:'I have been lived in Japan for last year.',
    explanation:'liveやknowは状態動詞でingを付けれないので現在完了を使う',
  },
  {
    check: 'G3_akenan_E',
    question:'「どれくらい～」の意味はどれか',
    a:'How long～',
    b:'How many～',
    c:'How much～',
    d:'How old～',
    explanation:'',
  },
  {
    check: 'G3_akenan_E',
    question:'「私は３年間中国語を勉強し続けている」の意味の英文はどれか',
    a:'I have studied Chinese for three years.',
    b:'I have been studying Chinese for three years.',
    c:'I has studies Chinese for three years.',
    d:'I has been studying Chinese for three years.',
    explanation:'現在完了進行形にすると、飲まず食わずで３年間勉強し続けている事になり\n現実的に不可能なので現在完了を使う',
  },
  {
    check: 'G3_akenan_E',
    question:'「昨日からずっと雨が降り続いてます」の意味の英文はどれか',
    a:'It has been raining since yesterday.',
    b:'It had been raining since yesterday.',
    c:'It have been raining since yesterday.',
    d:'It has been raining for yesterday.',
    explanation:'yesterdayの過去を表す単語があるが、hasをhadにしない',
  },
  {
    check: 'G3_akenan_E',
    question:'They clean this room every day.を受動態の文にすると正しいのはどれか',
    a:'This room is cleaned every day.',
    b:'This room was cleaned every day.',
    c:'This room is clean every day.',
    d:'This room was clean every day.',
    explanation:'主語がTheyやWeならby以下は省略可能',
  },
  {
    check: 'G3_akenan_E',
    question:'English are spoken all over the world.を能動態の文に',
    a:'People speak English all over the world.',
    b:'People speaks English all over the world.',
    c:'People spoke English all over the world.',
    d:'People are speaking English all over the world.',
    explanation:'書かれていないので主語にはpeopleやtheyを使う',
  },
  // 中３ 曙川南 数学
  {
    check: 'G3_akenan_M',
    question: '(x＋3)(x－7)＝？',
    a: 'x²－4x－21',
    b: 'x²＋4x＋21',
    c: 'x²－21x－4',
    d: 'x²＋10x＋21',
    explanation: '答え：x²－4x－21\n間違った人はしっかりと乗法公式を覚えなおしましょう！',
  },
  {
    check: 'G3_akenan_M',
    question: '(2x－1)²＝？',
    a: '4x²－4x＋1',
    b: '4x²＋4x－1',
    c: '4x²＋4x＋1',
    d: '4x²－4x－1',
    explanation: '答え：4x²－4x＋1\n間違った人はしっかりと乗法公式を覚えなおしましょう！',
  },
  {
    check: 'G3_akenan_M',
    question: '(4x－1)(4x＋1)＝？',
    a: '16x²－1',
    b: '16x²',
    c: '2x²－1',
    d: '16x²＋8x－1',
    explanation: '答え：4x²－4x＋1\n間違った人はしっかりと乗法公式を覚えなおしましょう！',
  },
  {
    check: 'G3_akenan_M',
    question: '9999²＝？',
    a: '99980001',
    b: '99999981',
    c: '99980981',
    d: '99988901',
    explanation: '答え：99980001\n9999＝10000－1なので、\n9999²＝(10000－1)²＝10000²－2×10000×1＋1\nこうすれば暗算でも解けますね。',
  },
  {
    check: 'G3_akenan_M',
    question: 'x²－10x－24＝？',
    a: '(x＋2)(x－12)',
    b: '(x＋4)(x－6)',
    c: '(x－4)(x－6)',
    d: '(x－2)(x＋12)',
    explanation: '答え：(x＋2)(x－12)\n間違った人はしっかりと因数分解の公式・乗法公式を覚えなおしましょう！',
  },
  {
    check: 'G3_akenan_M',
    question: '1001²－999²＝？',
    a: '4000',
    b: '9999',
    c: '2000',
    d: '19998',
    explanation: '答え：4000\n1001²－999²＝(1001＋999)(1001－999)＝2000×2\nこうすれば暗算でも解けますね。',
  },
  {
    check: 'G3_akenan_M',
    question: '連続する3つの奇数について、「最大の数の平方と最小の数の平方の差」を計算します。\n最小の数を(2x－1)とおいたとき、正しい式はどれ？',
    a: '(2x＋3)²－(2x－1)²',
    b: '(2x＋1)－(2x－1)',
    c: '{(2x＋3)－(2x－1)}²',
    d: '(2x＋1)(2x－1)',
    explanation: '答え：(2x＋3)²－(2x－1)²\n平方とは2乗のことです。\n最小の数が(2x－1)ですから、連続する3つの奇数は(2x－1)，(2x＋1)，(2x＋3)となりますね。',
  },

  // 中３ 曙川南 理科
  {
    check: 'G3_akenan_SI',
    question: '１つの細胞が２つ以上に分かれることを何というか。',
    a: '細胞分裂',
    b: '分解',
    c: '化合',
    d: '昇華',
    explanation: '',
  },
  {
    check: 'G3_akenan_SI',
    question: '細胞分裂をする前とした直後で、細胞１個の大きさはどうなっているか。',
    a: '小さくなっている',
    b: '大きくなっている',
    c: '変わらない',
    d: '細胞によって異なる',
    explanation: '生物の成長は、①細胞の数を増やす。②それぞれの細胞が元の大きさになる。ことによって行われます。',
  },
  {
    check: 'G3_akenan_SI',
    question: '細胞分裂のとき、核の中に見られるひものようなものを何というか。',
    a: '染色体',
    b: 'DNA',
    c: '遺伝子',
    d: '受精卵',
    explanation: '',
  },
  {
    check: 'G3_akenan_SI',
    question: 'タマネギの根で細胞分裂を観察するとき、塩酸であたためるのはなぜか。',
    a: '細胞同士を離れやすくするため',
    b: '細胞の重なりをなくすため',
    c: '核を染色して見やすくするため',
    d: '脱色するため',
    explanation: 'カバーガラスを指の腹で押すのは、細胞同士の重なりをなくすため。酢酸カーミン液などを滴下するのは、核を染色するためです。',
  },
  {
    check: 'G3_akenan_SI',
    question: 'タマネギの根の先端付近に存在し、細胞分裂が盛んにおこなわれている部分を何というか。',
    a: '成長点',
    b: '分裂点',
    c: '成長部',
    d: '分裂部',
    explanation: '',
  },
  {
    check: 'G3_akenan_SI',
    question: '雄と雌がかかわらない生殖のことを何というか。',
    a: '無性生殖',
    b: '有性生殖',
    c: '顕性生殖',
    d: '潜性生殖',
    explanation: '反対に、雄と雌がかかわる生殖を有性生殖といいます。',
  },
  {
    check: 'G3_akenan_SI',
    question: '雄と雌の生殖細胞の核が結びつくことを何というか。',
    a: '受精',
    b: '受粉',
    c: '化合',
    d: '合体',
    explanation: '',
  },
  {
    check: 'G3_akenan_SI',
    question: '生殖細胞をつくるときの、特別な細胞分裂を何というか。',
    a: '減数分裂',
    b: '体細胞分裂',
    c: '生殖分裂',
    d: '特別分裂',
    explanation: '',
  },
  {
    check: 'G3_akenan_SI',
    question: '減数分裂の前後で、染色体の数はどうなっているか。',
    a: '1/2になる',
    b: '1/3になる',
    c: '変わらない',
    d: '2倍になる',
    explanation: '',
  },
  {
    check: 'G3_akenan_SI',
    question: '受精卵は細胞分裂を繰り返しやがて何になるか。',
    a: '胚',
    b: '生物',
    c: '植物',
    d: '子ども',
    explanation: '動物も植物も、受精卵は細胞分裂を繰り返し、やがて胚になります',
  },
  {
    check: 'G3_akenan_SI',
    question: '動物の有性生殖において、受精卵から成体になるまでの過程を何というか。',
    a: '発生',
    b: '成長',
    c: '出産',
    d: '孵化',
    explanation: '',
  },
  {
    check: 'G3_akenan_SI',
    question: '生物のもつ形や性質などの特徴を何というか。',
    a: '形質',
    b: '外見',
    c: '見た目',
    d: '様子',
    explanation: '',
  },
  {
    check: 'G3_akenan_SI',
    question: '子が親の染色体をそのまま受け継ぐものとして正しいのは次のうちどれか。',
    a: '無性生殖',
    b: '有性生殖',
    c: '無性生殖と有性生殖',
    d: '無性生殖でも有性生殖でもない',
    explanation: '有性生殖では、子は両親から半分ずつ染色体を受け継ぎます。',
  },
  {
    check: 'G3_akenan_SI',
    question: '対立形質をもつ純系どうしをかけ合わせたとき、子に現れる方の形質を何というか。',
    a: '顕性形質',
    b: '潜性形質',
    c: '有性形質',
    d: '無性形質',
    explanation: '子に現れない方の形質を潜性形質といいます。',
  },
  {
    check: 'G3_akenan_SI',
    question: '遺伝子の本体をアルファベット3文字で表すと何か。',
    a: 'ＤＮＡ',
    b: 'ＤＨＡ',
    c: 'ＢＴＢ',
    d: 'ＰＥＴ',
    explanation: '',
  },
  {
    check: 'G3_akenan_SI',
    question: '丸い種子をつくる純系のエンドウと、しわのある種子をつくる純系のエンドウをかけ合わせてできた子を自家受粉して孫の代を得たとき、丸い種子としわのある種子の比はどうなるか。　',
    a: '3：1',
    b: '2：1',
    c: '1：1',
    d: '4：1',
    explanation: '',
  },

  // 中３ 曙川南 社会

  //// 中３ 南高安
  // 中３ 南高安 英語
  {
    check: 'G3_nantaka_E',
    question:'現在完了進行形の形はどれか',
    a:'have/has been 動詞のing形',
    b:'have/has 動詞の過去分詞形',
    c:'had 動詞の過去分詞形',
    d:'have/has be 動詞のing形',
    explanation:'形はhave/has been動詞のingで「ずっと～し続けている」と訳す',
  },
  {
    check: 'G3_nantaka_E',
    question:'受動態の形はどれか',
    a:'be動詞 動詞の過去分詞形',
    b:'一般動詞 動詞の過去分詞形',
    c:'be動詞　動詞の原形',
    d:'一般動詞 動詞の原形',
    explanation:'形はbe動詞 動詞の過去分詞形で「～される・～されている」と訳す',
  },
  {
    check: 'G3_nantaka_E',
    question:'「私は去年から日本に住み続けている」の意味の英文はどれか',
    a:'I have lived in Japan since last year.',
    b:'I have been lived in Japan since last year.',
    c:'I have lived in Japan for last year.',
    d:'I have been lived in Japan for last year.',
    explanation:'liveやknowは状態動詞でingを付けれないので現在完了を使う',
  },
  {
    check: 'G3_nantaka_E',
    question:'「どれくらい～」の意味はどれか',
    a:'How long～',
    b:'How many～',
    c:'How much～',
    d:'How old～',
    explanation:'',
  },
  {
    check: 'G3_nantaka_E',
    question:'「私は３年間中国語を勉強し続けている」の意味の英文はどれか',
    a:'I have studied Chinese for three years.',
    b:'I have been studying Chinese for three years.',
    c:'I has studies Chinese for three years.',
    d:'I has been studying Chinese for three years.',
    explanation:'現在完了進行形にすると、飲まず食わずで３年間勉強し続けている事になり\n現実的に不可能なので現在完了を使う',
  },
  {
    check: 'G3_nantaka_E',
    question:'「昨日からずっと雨が降り続いてます」の意味の英文はどれか',
    a:'It has been raining since yesterday.',
    b:'It had been raining since yesterday.',
    c:'It have been raining since yesterday.',
    d:'It has been raining for yesterday.',
    explanation:'yesterdayの過去を表す単語があるが、hasをhadにしない',
  },
  {
    check: 'G3_nantaka_E',
    question:'They clean this room every day.を受動態の文にすると正しいのはどれか',
    a:'This room is cleaned every day.',
    b:'This room was cleaned every day.',
    c:'This room is clean every day.',
    d:'This room was clean every day.',
    explanation:'主語がTheyやWeならby以下は省略可能',
  },
  {
    check: 'G3_nantaka_E',
    question:'English are spoken all over the world.を能動態の文に',
    a:'People speak English all over the world.',
    b:'People speaks English all over the world.',
    c:'People spoke English all over the world.',
    d:'People are speaking English all over the world.',
    explanation:'書かれていないので主語にはpeopleやtheyを使う',
  },
  // 中３ 南高安 数学
  {
    check: 'G3_nantaka_M',
    question: '(x＋3)(x－7)＝？',
    a: 'x²－4x－21',
    b: 'x²＋4x＋21',
    c: 'x²－21x－4',
    d: 'x²＋10x＋21',
    explanation: '答え：x²－4x－21\n間違った人はしっかりと乗法公式を覚えなおしましょう！',
  },
  {
    check: 'G3_nantaka_M',
    question: '(2x－1)²＝？',
    a: '4x²－4x＋1',
    b: '4x²＋4x－1',
    c: '4x²＋4x＋1',
    d: '4x²－4x－1',
    explanation: '答え：4x²－4x＋1\n間違った人はしっかりと乗法公式を覚えなおしましょう！',
  },
  {
    check: 'G3_nantaka_M',
    question: '(4x－1)(4x＋1)＝？',
    a: '16x²－1',
    b: '16x²',
    c: '2x²－1',
    d: '16x²＋8x－1',
    explanation: '答え：4x²－4x＋1\n間違った人はしっかりと乗法公式を覚えなおしましょう！',
  },
  {
    check: 'G3_nantaka_M',
    question: '9999²＝？',
    a: '99980001',
    b: '99999981',
    c: '99980981',
    d: '99988901',
    explanation: '答え：99980001\n9999＝10000－1なので、\n9999²＝(10000－1)²＝10000²－2×10000×1＋1\nこうすれば暗算でも解けますね。',
  },
  {
    check: 'G3_nantaka_M',
    question: 'x²－10x－24＝？',
    a: '(x＋2)(x－12)',
    b: '(x＋4)(x－6)',
    c: '(x－4)(x－6)',
    d: '(x－2)(x＋12)',
    explanation: '答え：(x＋2)(x－12)\n間違った人はしっかりと因数分解の公式・乗法公式を覚えなおしましょう！',
  },
  {
    check: 'G3_nantaka_M',
    question: '1001²－999²＝？',
    a: '4000',
    b: '9999',
    c: '2000',
    d: '19998',
    explanation: '答え：4000\n1001²－999²＝(1001＋999)(1001－999)＝2000×2\nこうすれば暗算でも解けますね。',
  },
  {
    check: 'G3_nantaka_M',
    question: '連続する3つの奇数について、「最大の数の平方と最小の数の平方の差」を計算します。\n最小の数を(2x－1)とおいたとき、正しい式はどれ？',
    a: '(2x＋3)²－(2x－1)²',
    b: '(2x＋1)－(2x－1)',
    c: '{(2x＋3)－(2x－1)}²',
    d: '(2x＋1)(2x－1)',
    explanation: '答え：(2x＋3)²－(2x－1)²\n平方とは2乗のことです。\n最小の数が(2x－1)ですから、連続する3つの奇数は(2x－1)，(2x＋1)，(2x＋3)となりますね。',
  },

  // 中３ 南高安 理科
  {
    check: 'G3_nantaka_SI',
    question: '１つの細胞が２つ以上に分かれることを何というか。',
    a: '細胞分裂',
    b: '分解',
    c: '化合',
    d: '昇華',
    explanation: '',
  },
  {
    check: 'G3_nantaka_SI',
    question: '細胞分裂をする前とした直後で、細胞１個の大きさはどうなっているか。',
    a: '小さくなっている',
    b: '大きくなっている',
    c: '変わらない',
    d: '細胞によって異なる',
    explanation: '生物の成長は、①細胞の数を増やす。②それぞれの細胞が元の大きさになる。ことによって行われます。',
  },
  {
    check: 'G3_nantaka_SI',
    question: '細胞分裂のとき、核の中に見られるひものようなものを何というか。',
    a: '染色体',
    b: 'DNA',
    c: '遺伝子',
    d: '受精卵',
    explanation: '',
  },
  {
    check: 'G3_nantaka_SI',
    question: 'タマネギの根で細胞分裂を観察するとき、塩酸であたためるのはなぜか。',
    a: '細胞同士を離れやすくするため',
    b: '細胞の重なりをなくすため',
    c: '核を染色して見やすくするため',
    d: '脱色するため',
    explanation: 'カバーガラスを指の腹で押すのは、細胞同士の重なりをなくすため。酢酸カーミン液などを滴下するのは、核を染色するためです。',
  },
  {
    check: 'G3_nantaka_SI',
    question: 'タマネギの根の先端付近に存在し、細胞分裂が盛んにおこなわれている部分を何というか。',
    a: '成長点',
    b: '分裂点',
    c: '成長部',
    d: '分裂部',
    explanation: '',
  },
  {
    check: 'G3_nantaka_SI',
    question: '雄と雌がかかわらない生殖のことを何というか。',
    a: '無性生殖',
    b: '有性生殖',
    c: '顕性生殖',
    d: '潜性生殖',
    explanation: '反対に、雄と雌がかかわる生殖を有性生殖といいます。',
  },
  {
    check: 'G3_nantaka_SI',
    question: '雄と雌の生殖細胞の核が結びつくことを何というか。',
    a: '受精',
    b: '受粉',
    c: '化合',
    d: '合体',
    explanation: '',
  },
  {
    check: 'G3_nantaka_SI',
    question: '生殖細胞をつくるときの、特別な細胞分裂を何というか。',
    a: '減数分裂',
    b: '体細胞分裂',
    c: '生殖分裂',
    d: '特別分裂',
    explanation: '',
  },
  {
    check: 'G3_nantaka_SI',
    question: '減数分裂の前後で、染色体の数はどうなっているか。',
    a: '1/2になる',
    b: '1/3になる',
    c: '変わらない',
    d: '2倍になる',
    explanation: '',
  },
  {
    check: 'G3_nantaka_SI',
    question: '受精卵は細胞分裂を繰り返しやがて何になるか。',
    a: '胚',
    b: '生物',
    c: '植物',
    d: '子ども',
    explanation: '動物も植物も、受精卵は細胞分裂を繰り返し、やがて胚になります',
  },
  {
    check: 'G3_nantaka_SI',
    question: '動物の有性生殖において、受精卵から成体になるまでの過程を何というか。',
    a: '発生',
    b: '成長',
    c: '出産',
    d: '孵化',
    explanation: '',
  },
  {
    check: 'G3_nantaka_SI',
    question: '生物のもつ形や性質などの特徴を何というか。',
    a: '形質',
    b: '外見',
    c: '見た目',
    d: '様子',
    explanation: '',
  },
  {
    check: 'G3_nantaka_SI',
    question: '子が親の染色体をそのまま受け継ぐものとして正しいのは次のうちどれか。',
    a: '無性生殖',
    b: '有性生殖',
    c: '無性生殖と有性生殖',
    d: '無性生殖でも有性生殖でもない',
    explanation: '有性生殖では、子は両親から半分ずつ染色体を受け継ぎます。',
  },
  {
    check: 'G3_nantaka_SI',
    question: '対立形質をもつ純系どうしをかけ合わせたとき、子に現れる方の形質を何というか。',
    a: '顕性形質',
    b: '潜性形質',
    c: '有性形質',
    d: '無性形質',
    explanation: '子に現れない方の形質を潜性形質といいます。',
  },
  {
    check: 'G3_nantaka_SI',
    question: '遺伝子の本体をアルファベット3文字で表すと何か。',
    a: 'ＤＮＡ',
    b: 'ＤＨＡ',
    c: 'ＢＴＢ',
    d: 'ＰＥＴ',
    explanation: '',
  },
  {
    check: 'G3_nantaka_SI',
    question: '丸い種子をつくる純系のエンドウと、しわのある種子をつくる純系のエンドウをかけ合わせてできた子を自家受粉して孫の代を得たとき、丸い種子としわのある種子の比はどうなるか。　',
    a: '3：1',
    b: '2：1',
    c: '1：1',
    d: '4：1',
    explanation: '',
  },
  // 中３ 南高安 社会







];

export { quizDataJp }